### ISSUE TITLE
Tkinter filedialog.askdirectory() freezing when importing pywinauto

### ISSUE THREAD

**Issue by rsteel1** [pywinauto/pywinauto#517] opened 2018-07-05 08:15 UTC
Hi,

I've logged this in the Python issue tracker already, but I've been told to follow up with you guys and see if it's something that can be fixed on your end.

https://bugs.python.org/issue34029

Essentially, when pywinauto is imported, the tkinter.filedialog.askdirectory() function freezes the application and doesn't open the askdirectory dialog.

From the bug:

Debugging a bit, the hang happens in Lib/tkinter/commondialog.py, line 43:
`s = w.tk.call(self.command, *w._options(self.options)) `

The value of self.command is 'tk_chooseDirectory', and w._options(self.options) just gives an empty tuple, so the actual call is:
`s = w.tk.call('tk_chooseDirectory', ())`

This means that the hang is within w.tk.call().

**Comment by vasily-v-ryabov** [comment] 2018-07-11 17:53
Hi @rsteel1 thanks for reporting this! I need some time to take a deeper look for this. Can't promise to do this in July, maybe in August.

**Comment by airelil** [comment] 2018-12-18 08:01
Hi @rsteel1, finally we got the chance to look into this issue. I was able to reproduce the reported problem on my Win8.1 64-bit machine with 64-bit Python 3.6 using the code below
```python
import pywinauto
import tkinter.filedialog
tkinter.filedialog.askdirectory()
```
Since this involves windows file dialogs I suspected that the origin of the problem is incompatible COM threading model. By default, pywinauto sets up the Multithreading COM model (MTA) on init if no other mode was defined prior to import of pywinauto or specified explicitly through ```sys.coinit_flags```. My guess is ```askdirectory``` call uses "appartment threaded model" that is incompatible with MTA mode that was defined during pywinauto import. So to solve the problem we should specify the appropriate threading model explicitly as in the example below:
```python
import sys
sys.coinit_flags = 2  # COINIT_APARTMENTTHREADED

import pywinauto
import tkinter.filedialog
tkinter.filedialog.askdirectory()
```

**Comment by airelil** [comment] 2018-12-31 00:40
@rsteel1 , @vasily-v-ryabov , should we close this issue? We may need to add these COM initialization gotchas to our docs, though. For example, create "Troubleshoting" chapter.

**Comment by vasily-v-ryabov** [comment] 2019-01-02 16:39
I think yes. We can close this after adding notes to the docs.

**Closed** 2019-01-06 08:40 UTC
Labels: documentation

**Comment by nihaalnz** [comment] 2021-01-03 17:02
What could be the reason that `askopenfilenames()` work and not `askdirectory()` and this was working all fine till I decided to use pyglet or something. But this isnt the first time I'm using all this together and it has worked.

**Comment by ilykos** [comment] 2021-04-27 05:50
This seems to be a pyglet issue. I am using Pyglet 1.5.15 and on python 3.7.

**Comment by xuejianma** [comment] 2022-11-24 17:35
> Hi @rsteel1, finally we got the chance to look into this issue. I was able to reproduce the reported problem on my Win8.1 64-bit machine with 64-bit Python 3.6 using the code below
> 
> ```python
> import pywinauto
> import tkinter.filedialog
> tkinter.filedialog.askdirectory()
> ```
> 
> Since this involves windows file dialogs I suspected that the origin of the problem is incompatible COM threading model. By default, pywinauto sets up the Multithreading COM model (MTA) on init if no other mode was defined prior to import of pywinauto or specified explicitly through `sys.coinit_flags`. My guess is `askdirectory` call uses "appartment threaded model" that is incompatible with MTA mode that was defined during pywinauto import. So to solve the problem we should specify the appropriate threading model explicitly as in the example below:
> 
> ```python
> import sys
> sys.coinit_flags = 2  # COINIT_APARTMENTTHREADED
> 
> import pywinauto
> import tkinter.filedialog
> tkinter.filedialog.askdirectory()
> ```

After using pyinstaller to convert my project to exe, I had the issue of freezing window when clicking open directory. Turns out I imported pywinauto in another file, and this solution does solve my problem. I added "import sys" and "sys.coinit_flags = 2". The new exe created by pyinstaller behaves normally now when I click the open directory. 👍

**Comment by rsteel1** [comment] 2022-11-24 17:37
I moved on from this long ago but thank you for looking into it, I enjoyed receiving the email! Good spot, and I hope anyone else who comes across this error finds this thread. Thank you :)

-------- Original Message --------

**Comment by theexcelrobin** [comment] 2024-06-26 12:50
`sys.coinit_flags = 2`
Including this solved this problem for me in customtkinter

**Comment by alisamie97** [comment] 2025-04-05 04:27
thanks @theexcelrobin that fixed my problem
the trick was to add it before importing `tkinter`
