### ISSUE TITLE
uia APP.kill() bug

### ISSUE THREAD

**Issue by meshuggahtas** [pywinauto/pywinauto#547] opened 2018-08-15 10:09 UTC
I'm not sure about this, but my observation is that `APP.kill()` depending on the state of the program throws an error or "halfly terminates" probably because of trying to press ESC on a non existing control/window.

Example 1 : windows magnifier. This only happens, when you click on the dropdown menu AND the window itself was focused.
Example 2 : OBS. This only happens, when the Stats dialog is open AND the OBS window itself was focused.
Example 3 : windows magnifier half termination -> simple example code is `APP = pywinauto.Application(backend="uia").start("magnify.exe")` and `APP.kill()`. If you have docked magnifier, the top of the screen remains "docked". Also I have high confidence in that the application still lingers in the background/memory (huge performance drop while writing this issue), have no idea if this is directly related to pywinatuo `APP.kill()`.

**Example 1 code (Make sure to rename "Nagyito" to Magnifier maybe, name of the window and "Nezetek" to Views maybe, the dropdown with 3 values):**
```
import pywinauto
from pywinauto import actionlogger
actionlogger.enable()

APP = pywinauto.Application(backend="uia").start("magnify.exe")
APP.Nagyito.set_focus() # name of the window maybe Magnifier
APP.Nagyito.Nezetek.click_input() # name of the dropdown maybe Views
APP.kill()
```
**Result of above code:**
```
2018-08-15 11:48:47,341 INFO: Started magnify.exe application.
2018-08-15 11:48:48,710 INFO: Clicked Button "Nézetek" by left button mouse click at (267, 354)
2018-08-15 11:48:49,165 INFO: Typed text to the Menu: {ESC}
Traceback (most recent call last):
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\uia_defines.py", line 232, in get_elem_interface
    iface = cur_ptrn.QueryInterface(cls_name)
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\comtypes\__init__.py", line 1158, in QueryInterface
    self.__com_QueryInterface(byref(iid), byref(p))
ValueError: NULL COM pointer access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 434, in close
    iface = self.iface_window
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 322, in iface_window
    return uia_defs.get_elem_interface(elem, "Window")
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
pywinauto.uia_defines.NoPatternInterfaceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/oliver.horvath/PycharmProjects/pywinautogithub/main4.py", line 10, in <module>
    APP.kill()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\application.py", line 1247, in kill
    win.close()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 440, in close
    self.type_keys("{ESC}")
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\base_wrapper.py", line 882, in type_keys
    self.verify_actionable()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\base_wrapper.py", line 626, in verify_actionable
    self.verify_visible()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\base_wrapper.py", line 649, in verify_visible
    raise ElementNotVisible()
pywinauto.base_wrapper.ElementNotVisible
```

**Example 2 is with OBS:**
1. Enable the option "Open Stats dialog on startup" in General, 2nd option maybe.
```
import pywinauto
from pywinauto import actionlogger
actionlogger.enable()

APP = pywinauto.Application(backend="uia").start(work_dir=r"C:\Program Files (x86)\obs-studio\bin\64bit", cmd_line=r"C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe")
APP.Dialog.set_focus() # OBS window
APP.kill()
```
**Result of above code:**
```
Traceback (most recent call last):
  File "C:/Users/oliver.horvath/PycharmProjects/pywinautogithub/main4.py", line 11, in <module>
    APP.kill()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\application.py", line 1247, in kill
    win.close()
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 434, in close
    iface = self.iface_window
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\controls\uiawrapper.py", line 322, in iface_window
    return uia_defs.get_elem_interface(elem, "Window")
  File "C:\Users\oliver.horvath\venv\pywinautogithub\lib\site-packages\pywinauto\uia_defines.py", line 231, in get_elem_interface
    cur_ptrn = element_info.GetCurrentPattern(ptrn_id)
_ctypes.COMError: (-2147220991, 'Az esemény nem tudott meghívni előfizetőt', (None, None, None, 0, None))
```
Translation of last line: "The event was unable to invoke a subscriber".

**Comment by vasily-v-ryabov** [comment] 2018-11-18 22:16
For the first example I could reproduce only `app.kill()` bug. `.set_focus()` worked for me though I caught `(740, 'CreateProcess', 'The requested operation requires elevation.')` and had to run Magnifier manually and then connect to it. It's very strange because my Python process was running as Administrator for sure. Haven't figured it out yet. One more hidden level of elevation?

Didn't try OBS Studio yet. But this issue is going to be the next.

**Comment by vasily-v-ryabov** [comment] 2018-11-18 22:19
Addional elevation might be a feature of pretty new Windows 10 RS4 I use: `Version 1803 (OS Build 17134.407)`.

**Comment by vasily-v-ryabov** [comment] 2018-12-16 22:17
@meshuggahtas Is it possible to test on [this branch of my fork](https://github.com/vasily-v-ryabov/pywinauto/tree/app_kill_bug)? It doesn't try to close anything now, it just kills the app. Nothing more.

**Comment by meshuggahtas** [comment] 2018-12-17 12:06
Using that branch:

Example 1:
- OK, works great, no null com pointer error in 20 runs.

Example 3:
- Okay, closing works and no memory issue (in the original issue, it was like some part of magnify still ran).
- Still remains docked when closing, which shouldn't be the case in normal operation (opening magnify from start menu for example and closing the application will remove the dock area from the top).

**Comment by vasily-v-ryabov** [comment] 2018-12-17 17:18
Method `.kill()` doesn't assume any chance for the app to perform any un-initialization like restoring window layout. If you want correct screen restore, use `app.Magnifier.close()` for particular window instead of `app.kill()` for the whole app.

**Comment by meshuggahtas** [comment] 2018-12-18 09:41
You are right. Example 2 also works flawlessly, so the bugs written in this issue are solved by that app_kill_bug tree :) (Issue can be closed)

**Comment by vasily-v-ryabov** [comment] 2018-12-18 10:45
@meshuggahtas thanks for testing it! I'm going to close it after PR merge.

**Comment by meshuggahtas** [comment] 2019-03-05 10:36
pywinauto 0.6.6 .kill(soft=True) sometimes throws this error: 

> ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers',  (None, None, None, 0, None))

**Full log:**
> Traceback (most recent call last):
>   File "C:/Users/oliver.horvath/PycharmProjects/pywinautogithub/main4.py", line 10, in <module>
>     APP.kill(soft=True)
>   File "C:\Users\oliver.horvath\venv\pywinautogithub\Lib\site-packages\pywinauto-app_kill_bug\pywinauto\application.py", line 1248, in kill
>     win.close()
>   File "C:\Users\oliver.horvath\venv\pywinautogithub\Lib\site-packages\pywinauto-app_kill_bug\pywinauto\controls\uiawrapper.py", line 434, in close
>     iface = self.iface_window
>   File "C:\Users\oliver.horvath\venv\pywinautogithub\Lib\site-packages\pywinauto-app_kill_bug\pywinauto\controls\uiawrapper.py", line 132, in __get__
>     value = self.fget(obj)
>   File "C:\Users\oliver.horvath\venv\pywinautogithub\Lib\site-packages\pywinauto-app_kill_bug\pywinauto\controls\uiawrapper.py", line 322, in iface_window
>     return uia_defs.get_elem_interface(elem, "Window")
>   File "C:\Users\oliver.horvath\venv\pywinautogithub\Lib\site-packages\pywinauto-app_kill_bug\pywinauto\uia_defines.py", line 231, in get_elem_interface
>     cur_ptrn = element_info.GetCurrentPattern(ptrn_id)
> _ctypes.COMError: (-2147220991, 'Az esemény nem tudott meghívni előfizetőt', (None, None, None, 0, None))

**Example code** where I get this error thrown after 1~10 tries (seems like a timing related problem):
```
import pywinauto, time
from pywinauto import actionlogger
actionlogger.enable()

for i in range(0,30):
    print(i)
    APP = pywinauto.Application(backend="uia").start("magnify.exe")
    APP.Nagyito.set_focus()
    APP.Nagyito.Nezetek.click()
    APP.kill(soft=True)
```

Otherwise the soft=True nicely closes the application (Magnify in my case),

**Comment by airelil** [comment] 2019-03-06 08:32
Thanks for the concise report. We probably, just need to handle gracefully the disapperead windows.

**Comment by airelil** [comment] 2020-01-29 01:07
I am not able to reproduce the problem on the latest '[atspi](https://github.com/pywinauto/pywinauto/pull/884/commits/b26ffb2c076121b3adde9990ec57083fa52932aa)' branch on my Win8.1. Had to use a bit modified code as below:
```python
# Must run as Administrator
import pywinauto, time, os
from pywinauto import actionlogger
actionlogger.enable()
os.environ.update({"__COMPAT_LAYER":"RUnAsInvoker"})

for i in range(0,30):
    print(i)
    APP = pywinauto.Application(backend="uia").start("magnify.exe").connect(path="magnify.exe")
    APP.Magnifier.set_focus()
    APP.Magnifier.Views.click()
    APP.kill(soft=True)
```

However, we still could make a fix in `HwndWrapper.close` and `UIAWrapper.close`. The both methods have to raise the same well-known exception. Probably - `WindowNotFoundError`. Then `Application.kill` can easily handle the error with a small fix:
```python
try:
    if hasattr(win, 'close'):
        win.close()
        continue
except WindowNotFoundError:
    self.actions.log('Failed to close top level window')
```
The same interface should be implemented when the similar `close` methods are added for Linux or MacOS backends

**Comment by vasily-v-ryabov** [comment] 2022-05-12 16:44
Closing as implemented in `atspi` branch. It helps us to track progress for 0.7.0 milestone. Thanks for understanding!

**Closed by vasily-v-ryabov** 2022-05-12 16:44 UTC
Labels: bug, Priority-Critical
