### ISSUE TITLE
i try to work with findwindows.find_elements and then convert it somehow to WindowSpecification

### ISSUE THREAD

**Issue by orabs** [pywinauto/pywinauto#402] opened 2017-08-22 15:37 UTC
hey. 
i got a problem to get elements in my testing, because every time that i use functions like Child_windows etc.   its say that i got more then 1 elements exception.
when i reach to the element with .children() function or by  hierarchy its very difficult and take a long time 
i found the wonderful function that call findwindows.find_elements  and its exactly what i looked for. but the problem is its return uia_element_info class and even if i convert it by .element function  it returns UIautomation class and i cant execute action like input_click and all build-in functions that pywinauto suggest.  i know it doesn't  a recommended function but its very useful for us .
there is any option to solve it , or even anther  solution

**Comment by vasily-v-ryabov** [comment] 2017-08-23 07:08
Hi @orabs `child_window(title="something", found_index=0)` will make the search unambiguous. There is also idea to implement flag `first_only=True` which should work faster, but it's in progress.

**Comment by orabs** [comment] 2017-08-23 12:56
Thank you very much for the fast answer.
there is any way to know how many elements there is ( I mean what is the maximum index for my query)
in my automation test I have a lot of check boxes that I should click on them but part of them shown only if I scroll down the problem is its too many check boxes for specify their names so I try get all check boxes and click on them and after that I should scroll down a few sub windows and them scroll the rest check boxes but its very complicated 

there is any easy way to do it with pywinauto ?

I attached two screen shots 

regards

![ss1](https://user-images.githubusercontent.com/24523263/29616863-7a36b5da-881b-11e7-9dca-5d46687963fd.PNG)
![afterscroll](https://user-images.githubusercontent.com/24523263/29616869-7e3de6bc-881b-11e7-9d2d-9ddd3a933b76.PNG)

**Comment by vasily-v-ryabov** [comment] 2017-08-23 20:59
It's possible to list elements using `.children()` or `.descendants()`. These methods accept optional arguments like `.descendants(control_type="CheckBox")` (but number of arguments is fewer than for `child_window`). Flag `visible_only=False` is available in `child_window` for specifications only. If you can't find the element with this flag, probably it even doesn't exist (by design of the target app).

`.children()` and `.descendants()` returns a plain list of wrappers (not specifications). The first method gets all immediate children, the second one walks the whole subtree.

**Comment by orabs** [comment] 2017-08-24 14:24
Great! Thanks!
I try to get the select focus element, I mean there is  any element on the application.
 after someone was click on him ,it has blue color selection,
 and i want to get this element without specify which element i wanna check.
there is any option to do it?

regards!

**Comment by vasily-v-ryabov** [comment] 2017-08-25 06:18
You can try method `.has_keyboard_focus()` for focused and non-focused check boxes. If it differs, they can be separated using `if` in list comprehension for `.children()/descendants()`.

**Comment by vasily-v-ryabov** [comment] 2017-09-02 10:13
Hi @orabs is that helped to resolve your issue? Can we close it?

**Comment by orabs** [comment] 2017-09-04 12:24
Yes !  Thanks a lot!
sorry for late answer

**Closed** 2017-09-04 12:27 UTC
Labels: question
