### ISSUE TITLE
KeyError on Import with Python 3.8.1 64-bit

### ISSUE THREAD

**Issue by WinterPhoenix96** [pywinauto/pywinauto#879] opened 2020-01-10 20:26 UTC
## Expected Behavior
You can import pywinauto and use it. In the example script below, "script ran successfully" will print.

## Actual Behavior
```
Traceback (most recent call last):
  File "E:\Python38_64\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'ctypes.c_long'>, <class 'comtypes.LP_POINTER(IUIAutomationTextRange)'>), 0)
```

## Steps to Reproduce the Problem

  1. Have Python 3.8.1 64-bit
  2. `pip install pywinauto`
  3. Attempt to `import pywinauto`

## Short Example of Code to Demonstrate the Problem
```
import pywinauto
print("script ran successfully")
```

## Specifications

  - Pywinauto version: 0.6.8 via `pip`
  - Python version and bitness: 3.8.1, 64-bit
  - Platform and OS: Windows 10 Pro, 64-bit, Version 1909, Build 18363.535

**Comment by Xhandsomeman** [comment] 2020-01-11 07:28
me too

**Comment by vasily-v-ryabov** [comment] 2020-01-11 13:55
The full traceback looks so:
```python
Traceback (most recent call last):
  File "C:\Python38_1_64\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IDispatch)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38_1_64\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Python38_1_64\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Python38_1_64\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Python38_1_64\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1433, in <module>
    IAccessible._methods_ = [
  File "C:\Python38_1_64\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Python38_1_64\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Python38_1_64\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

The reproducing script is very simple (without pywinauto):
```python
import comtypes.client
comtypes.client.GetModule('UIAutomationCore.dll')
```

The problem was already reported as #868 but the real problem is even not in comtypes. It's a missing feature in libffi (https://github.com/libffi/libffi/issues/33) that was workarounded in Python 3.8.1 here: https://github.com/python/cpython/pull/16799

I'm closing this issue as duplication. If you want to track this problem, leave a comment in issue #868.

**Closed by vasily-v-ryabov** 2020-01-11 13:55 UTC

**Comment by vasily-v-ryabov** [comment] 2020-01-11 13:56
Just rollback to Python 3.8.0 or earlier as a temporary workaround.
