### ISSUE TITLE
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None) )

### ISSUE THREAD

**Issue by nimuston** [pywinauto/pywinauto#296] opened 2017-01-26 08:52 UTC
Hi,

Is some situations i get this COMError. Any ideas?

Code i'm running
```
import pywinauto

def click_button(button):
    app = pywinauto.Application(backend='uia')
    appconnect = app.connect(path='software.exe')
    window = appconnect.window()
    window.set_focus()
    button = window.child_window(auto_id=button)
    wrapper = button.wrapper_object()
    wrapper.click_input()

click_button('ButtonName')
```

Error message:

```
Traceback (most recent call last):
  File "click_button.py", line 14, in <module>
    click_button('ButtonName')
  File "click_button.py", line 10, in click_button
    wrapper = button.wrapper_object()
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 249, in wrappe
r_object
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 239, in __reso
lve_control
  File "build\bdist.win-amd64\egg\pywinauto\timings.py", line 402, in wait_until
_passes
  File "build\bdist.win-amd64\egg\pywinauto\application.py", line 202, in __get_
ctrl
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 84, in find_el
ement
  File "build\bdist.win-amd64\egg\pywinauto\findwindows.py", line 208, in find_e
lements
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 270, in d
escendants
  File "build\bdist.win-amd64\egg\pywinauto\uia_element_info.py", line 249, in _
get_elements
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None)
)

```

**Comment by vasily-v-ryabov** [comment] 2017-01-31 19:14
Hmm... Never seen this in `descendants()` method. Looks like a bug in comtypes or even UIAutomationCore.dll. It's better to have this issue reproducible on some free downloadable application to debug it and maybe to workaround. Sorry, can't promise to include the fix into 0.6.1 (will publish soon).

**Comment by mwsluis** [comment] 2017-03-22 09:26
I also encounter this issue when selecting a listview item:

```
Traceback (most recent call last):
  File "mycode.py", line 227, in define_tool
    dlg_license.ListBox.AllRoundRuntime.select()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 511, in select self.iface_selection_item.Select()
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

**Comment by vasily-v-ryabov** [comment] 2017-03-22 16:13
Hi @mwsluis if you repeat this action 2 times in a loop with `try-except`, is that working second time?

**Comment by mwsluis** [comment] 2017-03-24 11:30
I'm using a custom function that just executes the function x times and I it still doesn't work throws an exception. This seems to solve the issue for now, I'll have to monitor and see if it happens again. FYI the error only occurred when the machine on which the automation ran was locked.

**Comment by vasily-v-ryabov** [comment] 2017-03-24 11:37
> FYI the error only occurred when the machine on which the automation ran was locked.

Ah, this might be important! I'll try to reproduce it on my side with method `.select()`.
Is it a WPF application? Or Qt? Or somewhat else?

**Comment by mwsluis** [comment] 2017-03-24 13:28
It uses .net so probably wpf.

**Comment by vasily-v-ryabov** [comment] 2017-04-01 11:04
It seems I could reproduce similar problem for WireShark application. Just leaving the traceback here:

```python
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 326, in RunScript
    exec codeObject in __main__.__dict__
  File ".\test_wireshark.py", line 135, in <module>
    generateDataFile(t_interval,interface_name,file_name)
  File ".\test_wireshark.py", line 30, in generateDataFile
    win.window(best_match="Stop").wrapper_object().click()
  File ".\pywinauto\application.py", line 252, in wrapper_object
    ctrls = self.__resolve_control(self.criteria)
  File ".\pywinauto\application.py", line 243, in __resolve_control
    criteria)
  File ".\pywinauto\timings.py", line 402, in wait_until_passes
    func_val = func(*args)
  File ".\pywinauto\application.py", line 207, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File ".\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
  File ".\pywinauto\findwindows.py", line 208, in find_elements
    cache_enable=True)
  File ".\pywinauto\uia_element_info.py", line 270, in descendants
    return self._get_elements(IUIA().tree_scope["descendants"], cond, cache_enable)
  File ".\pywinauto\uia_element_info.py", line 250, in _get_elements
    return elements_from_uia_array(ptrs_array, cache_enable)
  File ".\pywinauto\uia_element_info.py", line 47, in elements_from_uia_array
    return [UIAElementInfo(ptrs.GetElement(n), cache_enable) for n in range(ptrs.Length)]
ValueError: NULL COM pointer access
```

**Comment by dominic1p** [comment] 2017-04-18 09:57
For me this is 100% reproducible:
`File ".\pywinauto\uia_element_info.py", line 63, in __init__
    self._element = IUIA().iuia.ElementFromHandle(handle_or_elem)
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None)`

This happens always when I call UIAElementInfo(handle) with the handle being the handle from the Word 2010 Save-close dialog on Windows 7 (the dialog that pops up if you want to close Word with unsaved changes). The machine does not need to be locked for this to happen. On Windows 10 the same code works fine.

**Comment by vasily-v-ryabov** [comment] 2017-07-07 10:14
Hi @dominic1p can you try the same with 0.6.3?
@mwsluis @nimuston how about your issues with this new release?

**Comment by sawantvs** [comment] 2017-07-17 08:18
Yes. Issue is still present with 0.6.3


    ptrs_array = self._element.FindAll(tree_scope, cond)
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

**Comment by Ingustavo** [comment] 2017-07-24 09:48
Having the same issue on the windows 10
pywinauto == 0.6.3

`app.top_window().print_control_identifiers()`  - which prints first component and then crash, but if I put the same fragment in `try except` block, then second call do the job without errors
`failure = True
    while failure:
        try:
            app.top_window().print_control_identifiers()
            failure = False
        except:
            print("-----FAILURE-----")
            failure = True
`

**Comment by mwsluis** [comment] 2017-08-22 14:04
Upgraded our test machine to 0.6.3 and removed my workaround code. It seems to be running well. Can;t say for sure if the issue is solved though as it happened quite randomly. If it runs for a week or 2 without errors I'll be content :)

**Comment by mwsluis** [comment] 2017-08-23 09:02
It didn't :(

```
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

Traceback (most recent call last):   
  [...]   
  File "MyLibrary.py", line 294, in _select_inq_license
    dlg_license.TopPanel.ListBox.child_window(title=license_name, control_type="ListItem").select()   
  File "build\bdist.win32\egg\pywinauto\controls\uiawrapper.py", line 535, in select
    self.iface_selection_item.Select()

```

**Comment by vasily-v-ryabov** [comment] 2017-08-23 21:03
Hi @mwsluis, thanks for the attempt.

`[...]`
Is it possible to see the full traceback?

**Comment by vasily-v-ryabov** [comment] 2017-09-20 07:01
[One more report on StackOverflow](https://stackoverflow.com/questions/46303673/how-should-i-approach-debugging-null-com-pointer-access-errors) about similar issue.

**Comment by smtb1234** [comment] 2018-01-07 06:46
I experienced the same issue..
Can anyone help me please..
 File "pmca\usb\driver\windows\wpd.py", line 130, in _send
_ctypes.COMError: (-2147024865, 'A device attached to the system is not functioning.', (None, None, None, 0, None))

I am trying to install openmemories:tweak for my sony alpha and this happens all the time

**Comment by vasily-v-ryabov** [comment] 2018-01-21 12:15
Hi @smtb1234 sorry for delayed reply and thanks for the report! This message `A device attached to the system is not functioning` looks slightly different from `NULL COM pointer access`. More detailed steps to reproduce or full traceback would be very helpful.

Assume you're trying to automate an application that connects to Android phone to take some actions. there. But this app is running on Windows desktop, right?

**Comment by vasily-v-ryabov** [comment] 2018-01-21 18:24
0.6.4 is out. It should fix NULL COM pointer access. For other problems please open separate issues. Closing.

**Closed by vasily-v-ryabov** 2018-01-21 18:24 UTC
Labels: Priority-Critical, bug, help wanted

**Comment by bkk003** [comment] 2019-01-18 10:53
hi,

i am using pywinauto 0.6.4 , i get the COMError !!!

app = pywinauto.Application(backend="uia")
    app.start("C:\Tecnai\Exe\Service\PPHSControl.exe")
    window = app.window_(title=u'PPHSControl')
    window.wait('ready', timeout=5)
    # window.print_control_identifiers()
    button = window.child_window(title="Ramping settings...")

    button.click()

above is the code , the error pops when the button.click() is called

Traceback (most recent call last):
  File "C:/Projects/TestAutomation/TBricks/Interface/UI/TBrickUIApp.py", line 132, in <module>
    button.click()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uia_controls.py", line 116, in click
    self.invoke()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 496, in invoke
    self.iface_invoke.Invoke()
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

**Comment by vasily-v-ryabov** [comment] 2019-01-20 10:02
Hi @bkk003 this is `InvokePattern` implementation error on app side or might be issue with 64-bit/32-bit app and Python mismatch (though with very low probability). Use `.click_input()` which is more realistic user click with moving real mouse cursor.

**Comment by Ferced** [comment] 2021-05-09 01:54
I have the same issue, I have this code attached to a wheel it only happens when I spin it very fast. So I imagine it has something to do with running the code multiple times very fast.

Traceback (most recent call last):
  File "Desktop/Scripts/testKeyboard.py", line 46, in <module>
    listener.join()  # Join the listener thread to the main thread to keep waiting for keys
  File "C:\Users\FerCed\miniconda3\lib\site-packages\pynput\_util\__init__.py", line 259, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\FerCed\miniconda3\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\FerCed\miniconda3\lib\site-packages\pynput\_util\__init__.py", line 211, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\FerCed\miniconda3\lib\site-packages\pynput\keyboard\_win32.py", line 284, in _process
    self.on_press(key)
  File "C:\Users\FerCed\miniconda3\lib\site-packages\pynput\_util\__init__.py", line 127, in inner
    if f(*args) is False:
  File "Desktop/Scripts/testTeclado.py", line 30, in on_press
    volume.SetMasterVolumeLevelScalar(float(volume.GetMasterVolumeLevelScalar()) - 0.02,None)
_ctypes.COMError: (-2147024865, 'A device attached to the system is not functioning.', (None, None, None, 0, None))

**Comment by vasily-v-ryabov** [comment] 2021-05-14 07:55
Hi @Ferced can you explain how this `pynput` issue relates to pywinauto?

**Comment by iii9o** [comment] 2023-12-18 12:19
Have it been solved?

**Comment by iii9o** [comment] 2023-12-18 12:19
Has it been solved?
