### ISSUE TITLE
error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')

### ISSUE THREAD

**Issue by jagadeesh1983** [pywinauto/pywinauto#387] opened 2017-07-11 05:46 UTC
Hi,

I am using Python 2.7 (64 bit) with latest pyWinAuto version 0.6.3 (64 bit) on Windows 2012 R2 (64 bit) to automate 64-bit application.

I am getting following error when I try to launch 64-bit application ie pside.exe from mapped I drive through python code.
`error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')`

Note: I have mapped I drive as `\\SLCNAS562\ptqaquality` in this case.

Here is my Code sample:
```python
from pywinauto import application
import time
from pywinauto import tests
from pywinauto.findbestmatch import MatchError
from pywinauto import findwindows
from pywinauto.timings import Timings

app = application.Application().start('I:\\PT857\\ORACLE\\pt857-102-R2-retail\\bin\\client\\pside.exe -CT ORACLE -CS T57467N5  -CD T57467N5 -CO QEDMO -CP QEDMO')
```
Output:
```python
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\Pythonwin\pywin\framework\scriptutils.py", line 323, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=0)
  File "C:\Python27\Lib\site-packages\Pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 655, in run
    exec cmd in globals, locals
  File "C:\Work\pywinauto\testjk.py", line 1, in <module>
    from pywinauto import application
  File "C:\Python27\lib\site-packages\pywinauto-0.6.3-py2.7.egg\pywinauto\application.py", line 965, in start
    _warn_incorrect_binary_bitness(exe_name)
  File "C:\Python27\lib\site-packages\pywinauto-0.6.3-py2.7.egg\pywinauto\application.py", line 1350, in _warn_incorrect_binary_bitness
    handleprops.is64bitbinary(exe_name) and not is_x64_Python():
  File "C:\Python27\lib\site-packages\pywinauto-0.6.3-py2.7.egg\pywinauto\handleprops.py", line 184, in is64bitbinary
    binary_type = win32file.GetBinaryType(filename)
error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')
```
I have observed that the same error even if I use UNC path ie `\\SLCNAS562\ptqaquality` instead of I drive in above mentioned code.
However, If installed that 64-bit application in local machine then launch it then it works fine. ie
`app = application.Application().start('C:\\PT857\\ORACLE\\pt857-102-R2-retail\\bin\\client\\pside.exe -CT ORACLE -CS T57467N5  -CD T57467N5 -CO QEDMO -CP QEDMO')`.

Also observed that if one of the instance of that 64-bit application ie pside.exe is already launched before running the above code ie `app = application.Application().start('I:\\PT857\\ORACLE\\pt857-102-R2-retail\\bin\\client\\pside.exe -CT ORACLE -CS T57467N5  -CD T57467N5 -CO QEDMO -CP QEDMO')`
then code works fine. It will launch pside.exe from I drive path on running python code.

The issue "error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')" is observed when there is no instance of pside.exe is running in the box and when we try to launch it from I drive through python code. 

Please help me how to fix this issue as our requirement is to launch this application from mapped I drive.

Thanks,
Jagadeesh

**Comment by jagadeesh1983** [comment] 2017-07-11 05:47
Correction I drive as been mapped as \\SLCNAS562\ptqaquality

**Comment by jagadeesh1983** [comment] 2017-07-11 05:48
I drive = \\SLCNAS562\ptqaquality

**Comment by jagadeesh1983** [comment] 2017-07-11 05:51
I drive mapped as (backward slash)(backward slash)SLCNAS562(backward slash)ptqaquality.

It seems this editor is printing single slash even if I use double backward slash

**Comment by vasily-v-ryabov** [comment] 2017-07-12 06:54
Hi @jagadeesh1983 it looks very similar to #226 but it's probably not the same.

Can you try running the following from `cmd.exe`?
```
I:\PT857\ORACLE\pt857-102-R2-retail\bin\client\pside.exe -CT ORACLE -CS T57467N5 -CD T57467N5 -CO QEDMO -CP QEDMO
```
Do you see Windows message box with similar error?

**Comment by vasily-v-ryabov** [comment] 2017-07-12 07:46
Yes, this check for 64-bit binary was added in 0.5.x releases. What about this code?
```python
import win32file
win32file.GetBinaryType(r'I:\PT857\ORACLE\pt857-102-R2-retail\bin\client\pside.exe')
```

**Comment by jagadeesh1983** [comment] 2017-07-12 09:07
I ran your above code in pythonwin and it returned the value 6. I am not sure what does this 6 indicates.

**Comment by vasily-v-ryabov** [comment] 2017-07-12 09:42
Great, the problem is not in the binary file itself. Return value 6 might be OK.
Can you import pywinauto from source folder and print `filename` before this line?
```python
binary_type = win32file.GetBinaryType(filename)
```
Assume this variable (`filename`) is malformed somehow. If so, it's a bug in pywinauto obviously.

**Comment by jagadeesh1983** [comment] 2017-07-12 10:36
You mean i need to add print (filename) in is64bitbinary()  class as mentioned below:

def is64bitbinary(filename):
    """Check if the file is 64-bit binary"""
    import win32file
    binary_type = win32file.GetBinaryType(filename)

**Comment by jagadeesh1983** [comment] 2017-07-12 10:41
Also I would like to inform you that actual path of pside.exe application is I:\PT857\ORACLE\pt857-102-R2-retail\bin\client**\winx86\**pside.exe and not I:\PT857\ORACLE\pt857-102-R2-retail\bin\client\pside.exe

In my earlier comments I have ignored \winx86\ in the path because you might confuse this pside.exe is 32-bit application. But infact, this pside.exe is a 64-bit application and it is just that this in under \winx86\ folder structure.

**Comment by vasily-v-ryabov** [comment] 2017-07-12 15:28
> You mean i need to add print (filename) in is64bitbinary() class as mentioned below:

Correct. Please print this. It will show if `filename` is malformed on previous steps.

**Comment by jagadeesh1983** [comment] 2017-07-12 16:23
Below is the python code which I am running 
app = application.Application().start('I:\\PT857\\ORACLE\\pt857-102-R2-retail\\bin\\client\\winx86\\pside.exe')
and when i try to print filename before binary_type = win32file.GetBinaryType(filename) code then it prints the filename as I:\PT857\ORACLE\pt857-102-R2-retail\bin\client\winx86\pside.exe

Note: Though we have \winx86\ in the above path pside.exe is still a 64-bit application as mentioned before

**Comment by jagadeesh1983** [comment] 2017-07-12 16:26
It seems filename is not malformed in above case since its the same path which is passed as parameter to start() method. Please confirm.

**Comment by vasily-v-ryabov** [comment] 2017-07-12 16:51
Yes, the `filename` looks correct. And you've seen that direct call to `win32file.GetBinaryType(filename)` return correct value 6 (it's `SCS_64BIT_BINARY` constant as mentioned in [GetBinaryType docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364819(v=vs.85).aspx)). But you still have this error 193 inside pywinauto at the same time?

**Comment by jagadeesh1983** [comment] 2017-07-12 17:41
Sorry for causing confusion. Please ignore my previous comments about the output of direct call to win32file.GetBinaryType(filename).

When I run below code through pythonwin
import win32file
binary_type = win32file.GetBinaryType('I:\\PT857\\ORACLE\\pt857-102-R2-retail\\bin\\client\\winx86\\pside.exe')
print (binary_type)

then i still get below error.
error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')

It seems earlier one instance of pside.exe was already launched so I was getting the output as 6. My bad I didn't notice that instance of pside.exe opened earlier.  

Now I have ensured that there is no pside.exe instance running and when I run the above code then I m still getting error 193.

**Comment by jagadeesh1983** [comment] 2017-07-12 17:44
Please note as mentioned earlier when one of pside.exe instance is already opened then I am able to launch another pside.exe instance from I drive through python code. Reported issue occurs only when no instance of pside.exe running and when we try to launch pside.exe instance from I drive through python code.

**Comment by jagadeesh1983** [comment] 2017-07-14 09:08
Hi Vasily,

Did you get a chance to check on my previous comments/response.
I am still getting the error 193 when we make direct call to win32file.GetBinaryType(filename).

Thanks,
Jagadeesh

**Comment by vasily-v-ryabov** [comment] 2017-07-14 09:39
Hi @jagadeesh1983 had no chance yet. It looks like a bug in Win32 API so I'm thinking about a workaround. Will make it a warning also and proceed with running an app.

**Comment by jagadeesh1983** [comment] 2017-07-14 10:03
Thanks for the update.
So if this is a bug then the workaround that you have planned will be coming in new pywinauto version 0.6.4 or will this issue be fixed in pywinauto 0.6.3?

**Comment by vasily-v-ryabov** [comment] 2017-07-14 10:35
0.6.3 is already out. Can't republish it on PyPI. So the workaround will be in 0.6.4.

**Comment by jagadeesh1983** [comment] 2017-07-14 14:24
ok fine. Thanks for the confirmation.

**Comment by jagadeesh1983** [comment] 2017-07-14 14:25
Any idea when pywinauto 0.6.4 (64-bit) will be published to customers.

**Comment by vasily-v-ryabov** [comment] 2017-07-14 14:37
Current estimation is about the beginning of September. But I'll let you know once this workaround is merged to master.

**Comment by jagadeesh1983** [comment] 2017-07-14 14:46
Thanks for the update.

**Closed** 2018-07-25 20:17 UTC
Labels: bug
