### ISSUE TITLE
Can't use at window7 python3.8

### ISSUE THREAD

**Issue by jhui163** [pywinauto/pywinauto#889] opened 2020-02-05 13:01 UTC
## Expected Behavior
frist I install python3.8 in my window7 ,then input pip install pywinauto at cmd window.
I think the pywinauto ver is 0.6.4 .
at last , I input "import pywinauto" .

## Steps to Reproduce the Problem

  1.pip install pywinauto
  2.import pywinauto
  3.Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
Traceback (most recent call last):
  File "D:\Python38-32\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'ctypes.c_long'>, <class 'comtypes.LP_POINTER(IUIAutomationTextRange)'>), 0)

During handling of the above exception, another exception occurred:
...
uiautomationcore.dll
...

## Short Example of Code to Demonstrate the Problem
import pywinauto
## Specifications

  - Pywinauto version: 0.6.4
  - Python version and bitness: 3.8.1
  - Platform and OS:window 7 64,and 32

**Comment by vasily-v-ryabov** [comment] 2020-02-05 13:12
Duplicate of #868. Roll back to Python 3.8.0 or 3.7.5 for now. Next Python release will fix the issue.

**Closed by vasily-v-ryabov** 2020-02-05 13:12 UTC
Labels: 3rd-party issue, duplicate

**Comment by jhui163** [comment] 2020-02-05 13:23
thank you  i see . i searched it
