### ISSUE TITLE
ComboBox Item_texts Issue when using MS UI Automation API

### ISSUE THREAD

**Issue by rla006** [pywinauto/pywinauto#617] opened 2018-12-02 07:25 UTC
When Win32 API is used, the item texts of the ComboBox can be retrieved successfully with the function ComboBox.item_texts(). 

But when  MS UI Automation API is used, the actual item texts fail to return, but a blank value and "open"  are got. When print control identifiers, there are two sub controls under the ComboBox. One is Edit, and the other is Down Button. Is it a bug of MS UI Automation API for ComboBox?
Here is the identifiers info>
```
Pane - 'GCSS'    (L382, T99, R985, B630)
['GCSSPane', 'GCSS', 'Pane']
child_window(title="GCSS", control_type="Pane")
   | 
   | Dialog - 'Select User Profile'    (L494, T280, R873, B448)
   | ['Dialog', 'Select User Profile', 'Select User ProfileDialog']
   | child_window(title="Select User Profile", control_type="Window")
   |    | 
   |    | Edit - ''    (L583, T324, R855, B337)
   |    | ['', 'Edit', '0', '1', 'Edit0', 'Edit1']
   |    | child_window(auto_id="50001", control_type="Edit")
   |    | 
   |    | ComboBox - ''    (L583, T349, R855, B373)
   |    | ['2', 'ComboBox', 'ComboBoxClose']
   |    | child_window(auto_id="50002", control_type="ComboBox")
   |    |    | 
   |    |    | Edit - ''    (L586, T352, R835, B370)
   |    |    | ['3', 'Edit2']
   |    |    | child_window(auto_id="1001", control_type="Edit")
   |    |    | 
   |    |    | Button - 'Open'    (L839, T350, R854, B372)
   |    |    | ['Open', 'OpenButton', 'Button', 'Button0', 'Button1']
   |    |    | child_window(title="Open", auto_id="DropDown", control_type="Button")
```

**Comment by vasily-v-ryabov** [comment] 2018-12-02 08:36
It might be connected with #532. Some workaround mixing "win32" stuff into UIA ComboBoxWrapper is needed. I think it's relevant to combo boxes from WinForms and MFC apps, WPF combo boxes should work with current UIA ComboBoxWrapper.

**Comment by jduncan8142** [comment] 2018-12-14 22:02
This issue is as close as I've found to my issue hoping someone here might be able to help in some way. I have a program with a structure in inspect.exe as follows: 
```
Main Window Control 
    --> Pane Control 
        --> 2nd pane control inside first pane 
            --> 3rd pane control 
                --> 4th Pane control 
                    --> 5th pane control 
                        -->  combobox control (Infragistics.Win.UltraWinEditors.UltraComboEditor) 
                            --> 2nd "combobox" (shows as Infragistics.Win.EmbeddableTextBoxWithUIPermissions) 
                                --> this has a split button control "Open" and a List Control. 
```

The program functions as: 
In the main Window there is a left hand side pane with a node tree/folder structure and that updates the 2nd pane where there is a dropdown search panel/pane and within this is the combobox control I need to select a given value from. The values are set based on the columns in a database and this allow the user to filter the data shown in another pane. 

The text shown in the combobox by default is [None] and I can return that with `first_combo_box.texts()`. the second_combo_box returns a list with [None], [None] but using the controls listed for class `pywinauto.controls.uia_controls.ComboBoxWrapper(elem)` other than `texts()` returns an error. 

AttributeError: 'EditWrapper' object has no attribute 'item_count'

Here is a shot of the inspect.exe tree:
![inspect1](https://user-images.githubusercontent.com/22695960/50028805-72cd7b80-ffb6-11e8-90eb-c1c08273f153.png)

```
from pywinauto.application import Application

lp_file_path = "<Path_to_App>"

try:
    app = Application().connect(path=lp_file_path)
except:
    app = Application().start(lp_file_path)

while True:
    try:
        dlg = app.top_window()
        if dlg.child_window(auto_id="TextUsername").texts()[0] == "<user_id>" \
        and dlg.child_window(auto_id="Combo_ServerName").texts()[0] == "localhost" \
        and dlg.child_window(auto_id="TextPassword").texts()[0] == "":
            dlg.child_window(auto_id="ButtonOK").click()
            break
        else:
            dlg.child_window(auto_id="Combo_ServerName").texts()[0] = "localhost"
            dlg.child_window(auto_id="TextUsername").texts()[0] = "<user_id>"
            dlg.child_window(auto_id="TextPassword").texts()[0] = ""
    except:
        continue

dlg = app.top_window()
tree_root = dlg.child_window(auto_id="TreeView").tree_root()
sub_trees = tree_root.sub_elements()
for i in sub_trees:
    if "Orders" in i.text():
        print i.text()
        i.ensure_visible()
        i.select()

container = dlg.child_window(auto_id="AddInContainer")
orders = container.child_window(auto_id="Orders")
dock = orders.child_window(auto_id="DockableWindow1")
pane = dock.child_window(auto_id="PanelDropDown1")
cf = pane.child_window(auto_id="ComboField1")
cf.set_focus()
cf.click()
```

Here is the details for combobox:
```
How found:	Selected from tree...
Name:	""
ControlType:	UIA_ComboBoxControlTypeId (0xC353)
LocalizedControlType:	"combo box"
BoundingRectangle:	{l:1207 t:164 r:1321 b:185}
IsEnabled:	true
IsOffscreen:	false
IsKeyboardFocusable:	true
HasKeyboardFocus:	false
AccessKey:	""
ProcessId:	12516
RuntimeId:	[2A.202AA]
AutomationId:	"ComboField1"
FrameworkId:	"WinForm"
ClassName:	"WindowsForms10.Window.8.app.0.141b42a_r12_ad1"
NativeWindowHandle:	0x202AA
ProviderDescription:	"[pid:21120,hwnd:0x202AA Main:Nested [pid:12516,hwnd:0x202AA Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
IsPeripheral:	[Not supported]
LiveSettingProperty:	[Not supported]
IsPassword:	false
HelpText:	""
FlowsFrom:	[Not supported]
OptimizeForVisualContent:	[Not supported]
Annotation.AnnotationAuthor:	[Not supported]
Annotation.AnnotationTypeId:	[Not supported]
Annotation.Author:	[Not supported]
Annotation.DateTime:	[Not supported]
Annotation.Target:	[Not supported]
Drag.DropEffect:	[Not supported]
Drag.DropEffects:	[Not supported]
Drag.GrabbedItems:	[Not supported]
Drag.IsGrabbed:	[Not supported]
DropTarget.DropTargetEffect:	[Not supported]
DropTarget.DropTargetEffects:	[Not supported]
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	""
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	""
LegacyIAccessible.Role:	combo box (0x2E)
LegacyIAccessible.State:	focusable (0x100000)
LegacyIAccessible.Value:	"[None]"
ObjectModel.UnderlyingObjectModel:	[Error: calling getter for this property: hr=0xFFFFFFFF80070057 - The parameter is incorrect.]
SpreadsheetItem.AnnotationObjects:	[Not supported]
SpreadsheetItem.AnnotationTypes:	[Not supported]
SpreadsheetItem.Formula:	[Not supported]
Style.ExtendedProperties:	[Not supported]
Style.FillColor:	[Not supported]
Style.FillPatternColor:	[Not supported]
Style.FillPatternStyle:	[Not supported]
Style.Shape:	[Not supported]
Style.StyleId:	[Not supported]
Style.StyleName:	[Not supported]
Value.IsReadOnly:	false
Value.Value:	"[None]"
Transform2.CanZoom:	[Not supported]
Transform2.ZoomLevel:	[Not supported]
Transform2.ZoomMinimum:	[Not supported]
Transform2.ZoomMaximum:	[Not supported]
IsAnnotationPatternAvailable:	[Not supported]
IsDragPatternAvailable:	[Not supported]
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	[Not supported]
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	[Not supported]
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	false
IsScrollPatternAvailable:	false
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	[Not supported]
IsSpreadsheetPatternAvailable:	[Not supported]
IsStylesPatternAvailable:	[Not supported]
IsSynchronizedInputPatternAvailable:	false
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	[Not supported]
IsTextEditPatternAvailable:	[Not supported]
IsTextPatternAvailable:	false
IsTextPattern2Available:	[Not supported]
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	[Not supported]
IsValuePatternAvailable:	true
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
FirstChild:	"" combo box
LastChild:	"" combo box
Next:	"" combo box
Previous:	"" combo box
Other Props:	Object has no additional properties
Children:	"" combo box
Ancestors:	"" pane
	"Minimum units:" pane
	"" pane
	"" pane
	"" pane
	"<Application Name>" window
	"Desktop" pane
	[ No Parent ]
```


Using Python 2.7.15 64bit in Windows Server 2008 R2 & pywinauto 0.6.5
If there is any other info needed please let me know. Some value were removed or changed as this is a live application.

**Comment by airelil** [comment] 2018-12-15 02:19
From a quick glance, it seems that you use the default win32 backend. Did you consider trying 'uia' ?
```
app = Application(backend='uia').connect(path=lp_file_path)
```

**Comment by jduncan8142** [comment] 2018-12-20 16:12
Tried the uia backend but now I'm getting the below error:

```
Traceback (most recent call last):
  File "C:\Users\JN26633\Downloads\lp_test1.py", line 67, in <module>
    cf1.select("DeliveryNumber")
  File "C:\Python27\lib\site-packages\pywinauto\controls\uia_controls.py", line 158, in select
    self.expand()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 527, in expand
    self.iface_expand_collapse.Expand()
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 132, in __get__
    value = self.fget(obj)
  File "C:\Python27\lib\site-packages\pywinauto\controls\uiawrapper.py", line 210, in iface_expand_collapse
    return uia_defs.get_elem_interface(elem, "ExpandCollapse")
  File "C:\Python27\lib\site-packages\pywinauto\uia_defines.py", line 234, in get_elem_interface
    raise NoPatternInterfaceError()
NoPatternInterfaceError
```
There is for sure a DeliveryNumber entry in the combobox but still the only control that works is `texts()`

>>> cf1.children()
gives:

[<uiawrapper.UIAWrapper - 'Open', SplitButton, 3527539>, <uia_controls.ListViewWrapper - '', ListBox, 3527539>]

Tried the ListView controls and was unable to get much from it and couldn't get anything from the SplitButton.

**Comment by vasily-v-ryabov** [comment] 2018-12-22 15:41
Well, it seems not exact duplicate of #532. Is it possible to provide sample application with the same kind of combo box?

**Comment by vasily-v-ryabov** [comment] 2019-01-27 11:15
I've implemented workarounds for all methods of ComboBoxWrapper for WinForms apps. It can be early tested from this branch:
```
pip uninstall pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/prepare_0_6_6.zip
```
Will create PR after writing more unit tests.

**Closed** 2019-02-12 10:58 UTC
Labels: bug
