### ISSUE TITLE
While Im trying to open a application using pywinauto module,application is getting crashed!

### ISSUE THREAD

**Issue by praveenjami1996** [pywinauto/pywinauto#452] opened 2017-12-26 05:21 UTC
```python
from pywinauto import application
app=application.Application()
app.start(r"C:\Program Files (x86)\Led Control System V3\LedControlSystem.exe")
```

![image](https://user-images.githubusercontent.com/32703678/34347601-baafe200-ea2a-11e7-83a2-7e0d71036808.png)
Please help me out solving this problem

**Comment by airelil** [comment] 2017-12-30 07:57
@praveenjami1996 , you didn't provide any details: python version, operating system version, steps to reproduce the problem.... I'm, personally, never heard about "LedControlSystem" application... Did you try to run other apps with pywinauto ? Did you try to launch "LedControlSystem.exe" from command line or from a batch file (without pywinauto) ?

**Comment by vasily-v-ryabov** [comment] 2018-01-21 17:34
Hi @praveenjami1996, @airelil is right. Good technical description will save our time (and your time) so that we could help you faster.

Some applications may crash if Python is 32-bit and target application is 64-bit (or vice versa). It's strange that the app is crashing on startup because usually such failures happen while doing some actions with the GUI. But nothing is guaranteed if Python and app target architectures are different because sizes of internal structures are different as well.

I'd prefer to close this issue, but feel free to re-open with good technical description.

**Closed by vasily-v-ryabov** 2018-01-21 17:34 UTC
