### ISSUE TITLE
Tree Methods Don't Work?

### ISSUE THREAD

**Issue by TaylorSMarks** [pywinauto/pywinauto#93] opened 2015-09-29 00:34 UTC
Here's my code sample:

~~~
# Start the application
from subprocess import call
call(['compmgmt.msc'], shell = True)

# Get the window:
from pywinauto.controls.HwndWrapper import HwndWrapper
from pywinauto.findwindows          import find_window

w = HwndWrapper(find_window(title_re = 'Computer Management'))

# Get the list:
l = w.Children()[3]

# Find the Position of the first item (System Tools):
p = l.GetItemRect(0).mid_point()

# Double click it to enter it:
l.DoubleClick(coords = (p.x, p.y))

# Find the Position of the sixth item (Device Manager):
p = l.GetItemRect(5).mid_point()

# Double click it to enter it:
l.DoubleClick(coords = (p.x, p.y))

# Now crap moves around... you have a tree to work with...
t = w.Children()[6]

# And I seem to be bashing against a wall here... the tree class just doesn't seem to work.
print(t.ItemCount()) # Prints 102
# t.PrintItems() # Throws Exception
# t.Texts() # Throws Exception
# t.Root().Children() # Throws Exception
~~~

All of the exceptions that are thrown end the same:

  File "C:\Python27\lib\site-packages\pywinauto\controls\common_controls.py", line 1089, in _readitem
    raise ctypes.WinError()
WindowsError: [Error 2] The system cannot find the file specified.

I'm on Windows 7, 64 bit. Python is 2.7.9, 32 bit. PyWinAuto is 0.5.3.

**Comment by airelil** [comment] 2015-09-29 03:59
Hi @TaylorSMarks, I think you have the problem because you are trying to automate a 64-bit application with a 32-bit version of Python. You should switch to 64-bit version of Python. I reproduced your problem when I ran your automation script on 32-bit Python. It started working for me when I switched to 64-bit Python. Basically, if you'd use *application.start_* or *application.connect_* methods you'd got a warning about inappropriate Python architecture. However you didn't get it as you launched it with *subprocess.call*. 

I agree it's tricky to run the management console but I think you still should add to your script the following code to connect a pywinauto app to after the launch:
```python
import pywinauto
app = pywinauto.Application()
app.connect_(path="mmc.exe")
```

**Comment by vasily-v-ryabov** [comment] 2015-09-29 08:10
@TaylorSMarks , the code might look better when using `Application` object. This is working code for 64-bit Python:

```python
from __future__ import print_function
import time
from subprocess import Popen
import pywinauto

if pywinauto.sysinfo.is_x64_Python():
    Popen(['compmgmt.msc'], shell = True) # call(...) may block your Python script until mmc.exe closed
else:
    raise RuntimeError('Use 64-bit Python!')
time.sleep(3) # We will add a timeout parameter into Connect method later, so just wait explicitly
app = pywinauto.Application.Connect(path="mmc.exe")

system_tools = app.ComputerManagement.ListView.GetItem('System Tools')
system_tools.Click(double=True)
tree = app.ComputerManagement.TreeView
tree.GetItem(r'\Computer management\System tools\Device manager').Click(double=True)
# GetItem() is also resistant to typos

print(tree.Texts())
app.ComputerManagement.PrintControlIdentifiers() # prints nice access names for every available control
```

**Comment by vasily-v-ryabov** [comment] 2015-09-29 09:50
And one more trick for main menu:
```python
app.ComputerManagement.ToolbarFile.Button('&File').Click()
app.Window_(class_name='#32768').MenuItem('Options').ClickInput()
```

**Comment by lanzorg** [comment] 2015-10-08 22:34
I am going to create an application, compiled with pyinstaller.
It will automate gui of multiple **x86** and **x64** applications.
Some applications have treeviews and this issues bothers me.
What do you recommend to solve this problem?

**Comment by vasily-v-ryabov** [comment] 2015-10-09 05:26
Hi, @lanzorg. Currently we can only recommend using both 32-bit and 64-bit Pythons and switching between each other. We know, it's possible to implement mixed x86/x64 support from one Python, but there is plenty of work. Not this year.

**Comment by vasily-v-ryabov** [comment] 2015-10-11 18:46
@lanzorg, is a tree view the only show stopper for your x86/x64 mixed case? If yes, we may consider fixing it earlier.

**Comment by vasily-v-ryabov** [comment] 2016-04-16 16:33
@TaylorSMarks, @lanzorg, the issue with TreeView mixed case has been fixed in UIA branch. Could you please try it and let us know if it works or not?

**Comment by TaylorSMarks** [comment] 2016-04-16 17:10
@vasily-v-ryabov - I no longer have access to the computer where I had this issue before (it was on a work computer and I changed employers ~2 months ago.)

**Comment by vasily-v-ryabov** [comment] 2016-05-16 15:39
Closing since no more concerns for a month. If someone faces with the same issue, please re-open this or file another issue.

**Closed by vasily-v-ryabov** 2016-05-16 15:39 UTC
Labels: enhancement, question

**Comment by jagadeesh1983** [comment] 2017-06-20 14:53
Hi,

I am using Python 2.7 (64 bit) with pyWinAuto 0.4 (64 bit) on Windows 2012 R2 (64 bit) to automate 64-bit application.
I am getting following error while accessing Tree Method ie GetItem() to read TreeView items. 
ctypes.ArgumentError: argument 4: <type 'exceptions.OverflowError'>: long int too long to convert

Here is my code sample:

from pywinauto import application
import time
from pywinauto import tests
from pywinauto.findbestmatch import MatchError
from pywinauto import findwindows
from pywinauto.timings import Timings

app = application.Application()
app.start("I:\\PT857\\ORACLE\\pt857-101-r1-prj-stingray\\bin\\client\\winx86\\pside.exe -CT ORACLE -CD T57123N5 -CO QEDMO -CP QEDMO")
time.sleep(5)
app.window_(title_re = 'Application Designer - *').MenuSelect('File->New')
app.NewDefinition.ListBox.Select('Application Package')
time.sleep(1)
app.NewDefinition.OK.ClickInput()
app.window_(title_re = 'Application Designer - *').MenuSelect('Insert->Package')
app.Definition.PackageNameEdit.SetEditText('SubPackageB')
app.Definition.TypeKeys('{ENTER}')
app.window_(title_re='.*Application Designer.*').TreeView.GetItem('\(unnamed)\SubPackageB').State()


Output:

Traceback (most recent call last):
  File "C:\Users\jkanthar\workspace\TEST123\TreeView\AppPackage.py", line 18, in <module>
    app.window_(title_re='.*Application Designer.*').TreeView.GetItem('\(unnamed)\SubPackageB').State()
  File "C:\Python27\lib\site-packages\pywinauto\controls\common_controls.py", line 965, in GetItem
    texts = [r.Text() for r in roots]
  File "C:\Python27\lib\site-packages\pywinauto\controls\common_controls.py", line 549, in Text
    return self._readitem()[1]
  File "C:\Python27\lib\site-packages\pywinauto\controls\common_controls.py", line 839, in _readitem
    remote_mem)
ctypes.ArgumentError: argument 4: <type 'exceptions.OverflowError'>: long int too long to convert


However, same code is working fine on Windows 7 (64 bit) with Python 2.7 (64 bit) & pyWinAuto 0.4(64 bit).

I have observed that item.pszText under _readitem() function in common_controls.py is assigned a 64-bit Pointer in Windows 2012 R2 (64-bit) which is causing Overflow error when the entry is read through retval variable under _readitem().
Whereas in Windows 7 (64-bit), item.pszText under _readitem() function is assigned 32-bit Pointer due to which above code works in Windows 7 (64-bit).

Please help how to fix this issue in Windows 2012 R2 (64-bit).

Thanks,
Jagadeesh
