### ISSUE TITLE
Question: Does this work on Microsoft Surface Device

### ISSUE THREAD

**Issue by Prashant3100** [pywinauto/pywinauto#285] opened 2016-12-28 23:46 UTC
Hi, 
We have app on Microsoft Surface Device, Can we use 'pywinauto' to automate MS Surface Native/Hybrid app. 

If yes, Can you please provide more details How? 

-Thanks 
_PrashantN

**Comment by airelil** [comment] 2016-12-29 07:25
I personally, do not have any experience with Microsoft Surface devices. If the app supports MS UI Automation you have a chance. The latest pywinauto version 0.6 can be run with so called UIA backend. Please, let us know if you give it a try. Refer to our docs for more details : https://pywinauto.readthedocs.io/en/latest/

**Comment by Prashant3100** [comment] 2016-12-30 23:14
thanks will give it a try.

**Comment by vasily-v-ryabov** [comment] 2017-03-03 15:59
Hi @Prashant3100, is the question still actual? Did you have successful attempt?

**Comment by Prashant3100** [comment] 2017-03-08 06:28
Hi Vasily, 
Yes i tried this on Surface, But no luck, It works fine on Windows machine.

**Comment by vasily-v-ryabov** [comment] 2017-03-08 07:51
@Prashant3100 what was the problem? As I see in Google, Python should be available on Surface Pro (should work the sama as on Win8). So assume the problem is in UIAutomationCore.dll availability or in custom controls in Surface specific apps. Could find [this thread on SO](http://stackoverflow.com/questions/5491714/best-way-to-test-a-microsoft-surface-application) about automation peers.

**Comment by vasily-v-ryabov** [comment] 2018-01-25 17:20
OK, we're not going to support this device. Closing as "won't fix" for now. Might be re-opened if it will become possible one day.

**Closed by vasily-v-ryabov** 2018-01-25 17:20 UTC
Labels: question, wontfix
