### ISSUE TITLE
module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'

### ISSUE THREAD

**Issue by madhurjain** [pywinauto/pywinauto#513] opened 2018-06-28 05:15 UTC
Trying to use `pywinauto` for the very first time and stuck with this issue

**Environment** -
Windows 10 x64 Version 1709 (OS Build 16299.309)
Python 3.6.4 x64

**Installed pywinauto using pip** -
Successfully installed comtypes-1.1.4 pypiwin32-223 pywin32-223 pywinauto-0.6.4 six-1.11.0

my `pywinauto_test.py` script contains a single line
```python
from pywinauto.application import Application
```
Very first time I install `pywinauto` and run the `pywinauto_test.py` script, I get a _**ImportError: Typelib newer than module**_ error with below traceback
(I am running the script as administrator)

```
c:\testmachine>python pywinauto_test.py
Traceback (most recent call last):
  File "pywinauto_test.py", line 1, in <module>
    from pywinauto.application import Application
  File "C:\Python36\lib\site-packages\pywinauto\__init__.py", line 72, in <module>
    from . import findwindows
  File "C:\Python36\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Python36\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 46, in <module>
    from ..uia_defines import IUIA
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 172, in _CreateWrapper
    generate_module(tlib, ofi, pathname)
  File "C:\Python36\lib\site-packages\comtypes\tools\tlbparser.py", line 750, in generate_module
    gen.generate_code(list(items.values()), filename=pathname)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 241, in generate_code
    self.generate_all(items)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 189, in generate_all
    self.generate(item)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 701, in ComInterface
    self.generate(itf.get_head())
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 722, in ComInterfaceHead
    self.generate(base.get_head())
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 185, in generate
    mth(item)
  File "C:\Python36\lib\site-packages\comtypes\tools\codegenerator.py", line 629, in External
    comtypes.client.GetModule(ext.tlib)
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Python36\lib\site-packages\comtypes\gen\_00020430_0000_0000_C000_000000000046_0_2_0.py", line 397, in <module>
    from comtypes import _check_version; _check_version('')
  File "C:\Python36\lib\site-packages\comtypes\__init__.py", line 40, in _check_version
    raise ImportError("Typelib newer than module")
ImportError: Typelib newer than module
```

When I run `pywinauto_test.py` subsequent times, I get a _**module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'**_ error with below traceback

```
c:\testmachine>python pywinauto_test.py
Traceback (most recent call last):
  File "pywinauto_test.py", line 1, in <module>
    from pywinauto.application import Application
  File "C:\Python36\lib\site-packages\pywinauto\__init__.py", line 72, in <module>
    from . import findwindows
  File "C:\Python36\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Python36\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 46, in <module>
    from ..uia_defines import IUIA
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Python36\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'
```

**Comment by vasily-v-ryabov** [comment] 2018-06-29 21:28
Hi @madhurjain these are all `comtypes` issues. The fix for the second one is here: https://github.com/enthought/comtypes/pull/153

Root cause for the first error is probably Windows update so that `UIAutomationCore.dll` was updated. I think it can be handled on pywinauto side. Thanks for reporting this!

**Comment by vasily-v-ryabov** [comment] 2018-06-29 21:33
Anyway re-installing `comtypes==1.1.5` (hope it will be posted this weekend) should resolve the first issue as well, because post-install step will clear `comtypes` cache so old `UIAutomationCore.dll` wrapper will be removed and re-generated at the first usage.

**Comment by madhurjain** [comment] 2018-07-05 06:16
@vasily-v-ryabov `pywinauto` is working perfectly fine with `comtypes==1.1.5`
Thanks a bunch for releasing the fix quickly!

**Comment by vasily-v-ryabov** [comment] 2018-07-05 10:40
Cool! I think we can close this. Though `comtypes==1.1.5` has another problem with `pip install`, but it's comtypes issue anyway, that I will fix in 1.1.6.

**Closed by vasily-v-ryabov** 2018-07-05 10:40 UTC
Labels: bug

**Comment by vasily-v-ryabov** [comment] 2018-08-08 21:30
I've filed an issue in comtypes repo: https://github.com/enthought/comtypes/issues/161

**Comment by qqzhong** [comment] 2018-08-10 06:56
@vasily-v-ryabov 

After clear the cache, my test.py works, and thank you a lot!
BTW, I do not reinstall my python 3.6.5 x64 on Win 10.

**Comment by JattMones** [comment] 2019-12-17 19:10
I'm experiencing the errors mentioned above when trying to import pywinauto on my python virtualenv, although I have it working on my systems python environment (Not sure how this could be, I've tried uninstalling packages and reinstalling the exact same package versions onto the virtualenv that are on my system). 

After I install pywinauto and verify pywin32 was installed and I clear the comtypes cache, I get the following errors each time I try to import pywinauto (3 different errors each time):

1. `Z:\chud_python\py_env\lib\site-packages\comtypes\client\_code_cache.py", line 41, in _find_gen_dir
    from comtypes import gen
ImportError: cannot import name 'gen' from 'comtypes' (Z:\chud_python\py_env\lib\site-packages\comtypes\__init__.py` (a solution for this is suggested [here](https://stackoverflow.com/questions/3898670/cant-import-comtypes-gen))

2. `Z:\chud_python\py_env\lib\site-packages\comtypes\tools\codegenerator.py", line 625, in External
    modname = comtypes.client._generate._name_module(ext.tlib)
AttributeError: module 'comtypes.client' has no attribute '_generate'`

3. `Z:\chud_python\py_env\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'`

I've also seen the `ModuleNotFoundError: No module named 'comtypes.gen.stdole'` error when trying some of the fixes above. Any suggestions?

**Comment by JattMones** [comment] 2019-12-17 19:20
UPDATE: When I downgrade to 0.5.4, I don't get any errors when import pywinauto. However, I use the Desktop subpackage which was introduced in a 0.6.x update. When downgrading to 0.6.0, I receive the same errors as above.

**Comment by vasily-v-ryabov** [comment] 2019-12-18 11:59
@JattMones be careful with different Python versions when installing comtypes. Their `setup.py` script uses 2to3 conversion on the fly. So install comtypes to Python 3.x only from clean source code, not after Py2.7 installation. This might be not the case though.

I have no much time now to dive into `comtypes` code though I have admin rights to their repo. Maybe I'll return to it some day. :)

**Comment by vasily-v-ryabov** [comment] 2022-03-01 09:36
Hi @harika882 maybe issue #969 will help you with PyInstaller spec file.

**Comment by amirmiz** [comment] 2022-03-06 18:18
Hello,

Working on Pycharm (pipenv) with pywinauto was smooth until I also installed PyAutoGUI package.
Once this was done, I constantly receive:
`C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\Scripts\python.exe C:/Users/amir/PycharmProjects/OnsightTest/main.py
Traceback (most recent call last):
  File "C:\Users\amir\PycharmProjects\OnsightTest\main.py", line 5, in <module>
    from pywinauto.application import Application
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\amir\.virtualenvs\OnsightTest-q9iVwqeh\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'`

I went over all solutions online (currently having comtypes 1.1.12 installed, tried to downgrade to 1.1.10 but to no avail).
Please assist as I am currently stuck and do not have any hint how to proceed.

**Comment by beuaaa** [comment] 2022-03-07 08:30
Hi @amirmiz,

I had the same error (https://github.com/pywinauto/pywinauto/issues/961) before updating comptypes and clearing the cache. Now it works. I hope this helps.

**Comment by amirmiz** [comment] 2022-03-07 10:23
Thanks, @beuaaa.
I was running the same code in command line and it perfectly work. The issue is within PyCharm itself and my pipenv. And I don't know what is the problem.
This is the pip list from command line:
![image](https://user-images.githubusercontent.com/101062700/157012537-d0c4b490-945d-459d-af07-688d985797d8.png)

This is the pip list from within PyCharm Terminal:
![image](https://user-images.githubusercontent.com/101062700/157012693-21e96ff9-ac5b-4e3e-b043-d79b75ca1138.png)

The main difference is that in cmd I also installed PyAutoGui, which was not yet done in PyCharm.

Please advise me what am I missing in PyCharm?
