### ISSUE TITLE
cannot get the child controls

### ISSUE THREAD

**Issue by hastelloy** [pywinauto/pywinauto#268] opened 2016-11-17 14:36 UTC
I am trying with pywinauto to work with SAP...

Through the code below, successfully connect with the app and the tab area in the BOM dialog could be found
```
import pywinauto
from pywinauto.application import Application

app = Application().connect(title_re=".*SAP Logon.*")
bom_dlg = app.window(title_re=".*BOM.*")
bom_dlg.print_control_identifiers(depth=2)
bottom = bom_dlg[u'Afx:5DF50000:1008']
bottom.draw_outline()
```
![bom](https://cloud.githubusercontent.com/assets/5629558/20392075/3688865a-ad11-11e6-9586-9437eb8b7f78.jpg)

Then to get the controls under the tab area, I tried to print out the child elements with 
`bottom.print_control_identifiers(depth=2)`
it gives out
```
Afx:5DF50000:1008 - ''    (L615, T197, R1292, B631)
<pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37C30>
[u'', u'1', u'0', u'Afx:5DF50000:1008']
child_window(class_name="Afx:5DF50000:1008")
   | 
   | Custom Container Class - 'Custom  Container'    (L618, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37B50>
   | [u'Custom  Container', u'Custom  Container1', u'Custom Container Class1', u'Custom Container Class0', u'Custom Container Class', u'Custom  ContainerCustom Container Class0', u'Custom  ContainerCustom Container Class1', u'Custom  Container0', u'Custom  ContainerCustom Container Class']
   | child_window(title="Custom  Container", class_name="Custom Container Class")
   | 
   | Shell Window Class - 'Control  Container'    (L618, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37790>
   | [u'Control  ContainerShell Window Class1', u'Control  ContainerShell Window Class0', u'Shell Window Class1', u'Shell Window Class0', u'Shell Window Class', u'Control  ContainerShell Window Class', u'Control  Container', u'Control  Container1', u'Control  Container0']
   | child_window(title="Control  Container", class_name="Shell Window Class")
   | 
   | AfxOleControl100 - ''    (L618, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37F70>
   | [u'AfxOleControl1000', u'AfxOleControl1001', u'2', u'AfxOleControl100']
   | child_window(class_name="AfxOleControl100")
   | 
   | AfxMDIFrame100 - ''    (L618, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37FD0>
   | [u'AfxMDIFrame100', u'3']
   | child_window(class_name="AfxMDIFrame100")
   | 
   | AfxFrameOrView100 - ''    (L618, T205, R772, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B377D0>
   | [u'4', u'AfxFrameOrView1001', u'AfxFrameOrView1000', u'AfxFrameOrView100']
   | child_window(class_name="AfxFrameOrView100")
   | 
   | Custom Container Class - 'Custom  Container'    (L618, T205, R772, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B377F0>
   | [u'Custom Container Class2', u'Custom  ContainerCustom Container Class2', u'Custom  Container2']
   | child_window(title="Custom  Container", class_name="Custom Container Class")
   | 
   | Shell Window Class - 'Control  Container'    (L618, T205, R772, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37830>
   | [u'Control  ContainerShell Window Class2', u'Shell Window Class2', u'Control  Container2']
   | child_window(title="Control  Container", class_name="Shell Window Class")
   | 
   | AfxOleControl100 - ''    (L618, T205, R772, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37870>
   | [u'AfxOleControl1002', u'5']
   | child_window(class_name="AfxOleControl100")
   | 
   | SAPTreeList - 'SAP's Advanced Treelist'    (L619, T206, R771, B604)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37450>
   | [u'SAPTreeList', u"SAP's Advanced Treelist", u"SAP's Advanced TreelistSAPTreeList"]
   | child_window(title="SAP's Advanced Treelist", class_name="SAPTreeList")
   | 
   | ScrollBar - ''    (L619, T604, R754, B621)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B378B0>
   | [u'6', u'ScrollBar']
   | child_window(class_name="ScrollBar")
   | 
   | AfxFrameOrView100 - ''    (L776, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B378F0>
   | [u'7', u'AfxFrameOrView1002']
   | child_window(class_name="AfxFrameOrView100")
   | 
   | Custom Container Class - 'Custom  Container'    (L776, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37930>
   | [u'Custom  ContainerCustom Container Class3', u'Custom Container Class3', u'Custom  Container3']
   | child_window(title="Custom  Container", class_name="Custom Container Class")
   | 
   | Shell Window Class - 'Control  Container'    (L776, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B37390>
   | [u'Control  ContainerShell Window Class3', u'Shell Window Class3', u'Control  Container3']
   | child_window(title="Control  Container", class_name="Shell Window Class")
   | 
   | SAPImage - ''    (L776, T205, R1289, B622)
   | <pywinauto.controls.hwndwrapper.HwndWrapper object at 0x04B2B0F0>
   | [u'8', u'SAPImage']
   | child_window(class_name="SAPImage")
```

To access the child, I tried several methods,

- __getitem__

```
bottom[u'AfxOleControl1000'].draw_outline()
````
it raise error:
```
  File "C:\usr\work\SAPScript\pywinauto\test_pywinauto.py", line 32, in <module>
    bottom[u'AfxOleControl1000'].draw_outline()
  File "c:\usr\Python27\lib\site-packages\pywinauto\application.py", line 304, in __getitem__
    raise AttributeError(message)
AttributeError: The control does not have a __getitem__ method for item access (i.e. ctrl[key]) so maybe you have requested this in error?
```
- child_window
```
Traceback (most recent call last):
  File "C:\usr\work\SAPScript\pywinauto\test_pywinauto.py", line 32, in <module>
    bottom.child_window(class_name="AfxOleControl100").draw_outline()
  File "c:\usr\Python27\lib\site-packages\pywinauto\application.py", line 346, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "c:\usr\Python27\lib\site-packages\pywinauto\application.py", line 239, in __resolve_control
    raise e.original_exception
pywinauto.findwindows.ElementNotFoundError: {'class_name': 'AfxOleControl100', 'top_level_only': False, 'parent': <pywinauto.win32_element_info.HwndElementInfo object at 0x04A262F0>, 'backend': u'win32'}
```

- Even tried to get the child control_id and find with it, cannot find it also.
```
for child in bottom.children():
    pywinauto.findwindows.find_element(control_id=child.control_id(), parent=bom_dlg).draw_outline()
```
```
  File "C:\usr\work\SAPScript\pywinauto\test_pywinauto.py", line 38, in <module>
    pywinauto.findwindows.find_element(control_id=child.control_id()).draw_outline()
  File "c:\usr\Python27\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'control_id': 92062304}
```

Any idea on what's wrong with my code or any workaround to get the controls?

**Comment by mborus** [comment] 2016-11-17 15:03
I'm having a lot of similar problems with a competing windows financial system.
Even "print_control_identifiers()" crashes on me.

My temporary solution. Ignore the children where I don't have access by catching all errors.

        mywin = findwindows.find_windows(title='REMOVEDNAMEOFSOFTWARE')

        if not mywin:
            print('Software not found.')
            continue

        for handle in mywin:
            print('\nhandle {}'.format(handle))
            try:
                app = Application().connect(handle=handle)
                mywin = app.window(handle=handle)
            except (pywintypes.error, RuntimeError) as e:
                # runtimerror if handle does not exist
                print ('{}'.format(e))  
                continue

            try:
                print(mywin)
                print(mywin.texts())
                restore = False

                for x in mywin.descendants():
                    for y in x.texts():
                        print(y)     
                    if 'SEARCHTEXT REMOVED' in x.texts()[0]:
                        print('OK')
                        restore = True
            except InvalidWindowHandle as e:
                print ('{}'.format(e))  
                pass

**Comment by airelil** [comment] 2016-11-17 20:30
@hastelloy,  a window spec chain that you try tor create for accessing the u'AfxOleControl1000' control is too long. The main principle is "Dialog->Control" but in you case you created "Dialog->control->control".  (```bom_dlg[u'Afx:5DF50000:1008'][u'AfxOleControl1000']```) This is why you get the exception.  Try to access your control directly through the dialog: ```bom_dlg[u'AfxOleControl1000']```

**Comment by hastelloy** [comment] 2016-11-17 23:52
@mborus 
your temp solution doesn't work for me because most of the texts of the controls are empty and I cann't find the control through this


@airelil 

'bom_dlg[u'AfxOleControl1000'].draw_outline()'


```
Traceback (most recent call last):
  File "C:\usr\work\SAPScript\pywinauto\test_pywinauto.py", line 33, in <module>
    bom_dlg[u'AfxOleControl1000'].draw_outline()
  File "c:\usr\Python27\lib\site-packages\pywinauto\application.py", line 346, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "c:\usr\Python27\lib\site-packages\pywinauto\application.py", line 239, in __resolve_control
    raise e.original_exception
pywinauto.findbestmatch.MatchError: Could not find 'AfxOleControl1000' in '[u'', u'ComboBox', u'Afx:5DF50000:8:00010003:00000010:00000000', u'1', u'0', u'3', u'2', u'AfxWnd100', u'4', u'7', u'6', u'9', u'5', u'Afx:5DF50000:1008', u'Afx:5DF50000:0:00010003:00000010:00000000', u'Edit', u'Button', u'AfxWnd1001', u'AfxWnd1000', u'AfxWnd1002', u'Button2', u'Button1', u'Button0', u'8', u'10', u'Afx:5DF50000:8:00010003:00000000:00000000']'
```

**BTW**
What is the right way to find a control in a complicated window except `print_control_identifiers` and `draw_outline`

**FYI**
below code is what recorded by the internal VBS recorder in SAP. Is this helpful for providing any information?

`session.findById("wnd[0]/usr/tabsTABSTRIP_TBL/tabpTAB1/ssub%_SUBSCREEN_TBL:ZENGR_REP001_RELEASED_BOM:9001/chkP_MLVL").selected = true
session.findById("wnd[0]/usr/tabsTABSTRIP_TBL/tabpTAB1/ssub%_SUBSCREEN_TBL:ZENGR_REP001_RELEASED_BOM:9001/ctxtS_MATNR-LOW").text = WScript.Arguments(0)`

first line is for the 'Multilevel' checkbox
the second for the editbox of 'Material'

**Comment by airelil** [comment] 2016-11-18 00:24
@hastelloy, maybe u'5'? It seems as it has been listed by print_control_identifiers in your first comment and in your last exception message. 

Usually we use Inspect.exe utility from Ms to examine the controls hierarchy. It works in the native and UI Automation mode. So you can check which mode works better for your application and use the appropriate pywinauto backend (win32 or UIA) 

PS: I suppose you work with pywinauto. 0.6

**Comment by vasily-v-ryabov** [comment] 2016-11-18 07:40
Hi @hastelloy, thanks for reporting this. It looks like a bug for me, but I need to investigate it in more details. I can try similar thing on our samples. But if you were provided simple MFC app reproducing exactly the same problems, it would be faster on our side.

@airelil just to be more precise... `Inspect.exe` can work in `MSAA` and `UIA` mode. `MSAA` is not the same as `backend="win32"` in pywinauto. Win32 controls can be examined with Spy++ tool shipped with Visual Studio (can be found through Start menu).

> PS: I suppose you work with pywinauto. 0.6

`depth=2` is not present in 0.5.4. So it's probably 0.6.0 or master branch at some moment.

**Comment by hastelloy** [comment] 2016-11-18 08:49
@airelil @vasily-v-ryabov 

tried with `u'2'` (corresponding to `u'AfxOleControl1000'`), it is not any control within the tab box,
anyway, `u'AfxOleControl1000'` should also be searchable since it is the identifier too, right?

![u2](https://cloud.githubusercontent.com/assets/5629558/20423639/7bf519c4-adac-11e6-9112-8f52f16da1aa.jpg)

Poor me... the SAP app is installed in company PC with strict IT restrictions (thanks for the great company, great productivity...) so got no chance to install Windows SDK to have Inspect.exe (could it be possible to have a standalone exe without the SDK?) . I searched another similar one Automation Spy. No controls could be found from the panel also.

![bom](https://cloud.githubusercontent.com/assets/5629558/20424008/8c76559a-adae-11e6-90f2-326ed011de51.png)

Yes, I am using 0.60 through pip.

Will try to play with some other simple app to see if it could be reproduced...

**Comment by vasily-v-ryabov** [comment] 2016-11-18 09:24
> could it be possible to have a standalone Inspect.exe without the SDK?

It can be copied from another machine. Standalone executable should work without any additional dlls.

**Comment by hastelloy** [comment] 2016-11-18 13:01
got Inspect.exe, should be those control are not standard MFC controls? If it is true, I can only come back to use python calling the internal VBS recorded.


```
How found:	Focus
	hwnd=0x0001053E 32bit class="Afx:61EF0000:1008" style=0x56100000 ex=0x10
RuntimeId:	"[42.66878]"
BoundingRectangle:	{l:726 t:232 r:1322 b:619}
ProcessId:	5520
ControlType:	UIA_PaneControlTypeId (0xC371)
LocalizedControlType:	"pane"
Name:	""
AcceleratorKey:	[Not supported]
AccessKey:	""
HasKeyboardFocus:	true
IsKeyboardFocusable:	true
IsEnabled:	true
AutomationId:	"100"
ClassName:	"Afx:61EF0000:1008"
HelpText:	""
ClickablePoint:	[Not supported]
Culture:	[Not supported]
IsControlElement:	[Not supported]
IsContentElement:	[Not supported]
LabeledBy:	[Not supported]
IsPassword:	false
NativeWindowHandle:	0x1053E
ItemType:	[Not supported]
IsOffscreen:	false
Orientation:	[Not supported]
FrameworkId:	"Win32"
IsRequiredForForm:	[Not supported]
ItemStatus:	[Not supported]
AriaRole:	[Not supported]
AriaProperties:	[Not supported]
IsDataValidForForm:	[Not supported]
ControllerForProperty:	[Not supported]
DescribedBy:	[Not supported]
FlowsTo:	[Not supported]
ProviderDescription:	"[pid:6036,hwnd:0x1053E Main:Nested [pid:5520,hwnd:0x1053E Annotation(parent link):Microsoft: Annotation Proxy (unmanaged:uiautomationcore.dll); Main:Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Nonclient:Microsoft: Non-Client Proxy (unmanaged:uiautomationcore.dll); Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
Value.IsReadOnly:	[Not supported]
Value.Value:	[Not supported]
RangeValue.Value:	[Not supported]
RangeValue.IsReadOnly:	[Not supported]
RangeValue.Minimum:	[Not supported]
RangeValue.Maximum:	[Not supported]
RangeValue.LargeChange:	[Not supported]
RangeValue.SmallChange:	[Not supported]
Scroll.HorizontalScrollPercent:	0.000000
Scroll.HorizontalViewSize:	71.121718
Scroll.VerticalScrollPercent:	0.000000
Scroll.VerticalViewSize:	100.000000
Scroll.HorizontallyScrollable:	true
Scroll.VerticallyScrollable:	false
Selection.Selection:	[Not supported]
Selection.CanSelectMultiple:	[Not supported]
Selection.IsSelectionRequired:	[Not supported]
Grid.RowCount:	[Not supported]
Grid.ColumnCount:	[Not supported]
GridItem.Row:	[Not supported]
GridItem.Column:	[Not supported]
GridItem.RowSpan:	[Not supported]
GridItem.ColumnSpan:	[Not supported]
GridItem.ContainingGrid:	[Not supported]
Dock.DockPosition:	[Not supported]
ExpandCollapse.ExpandCollapseState:	[Not supported]
MultipleView.CurrentView:	[Not supported]
MultipleView.SupportedViews:	[Not supported]
Window.CanMaximize:	[Not supported]
Window.CanMinimize:	[Not supported]
Window.WindowVisualState:	[Not supported]
Window.WindowInteractionState:	[Not supported]
Window.IsModal:	[Not supported]
Window.IsTopmost:	[Not supported]
SelectionItem.IsSelected:	[Not supported]
SelectionItem.SelectionContainer:	[Not supported]
Table.RowHeaders:	[Not supported]
Table.ColumnHeaders:	[Not supported]
Table.RowOrColumnMajor:	[Not supported]
Table.ItemRowHeaderItems:	[Not supported]
Table.ItemColumnHeaderItems:	[Not supported]
Toggle.ToggleState:	[Not supported]
Transform.CanMove:	[Not supported]
Transform.CanResize:	[Not supported]
Transform.CanRotate:	[Not supported]
IsDockPatternAvailable:	false
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsMultipleViewPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollPatternAvailable:	true
IsScrollItemPatternAvailable:	false
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsTablePatternAvailable:	false
IsTableItemPatternAvailable:	false
IsTextPatternAvailable:	false
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsValuePatternAvailable:	false
IsWindowPatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsVirtualizedItemPatternAvailable:	false
FirstChild:	[null]
LastChild:	[null]
Next:	(null) title bar
Previous:	"Please enter Material No." pane
Other Props:	Object has no additional properties
Children:	Container has no children
Ancestors:	"Released BOM Printout" window
	"Desktop" pane
	[ No Parent ]
```

One interesting thing, class of the tab panel looks like dynamic, but it is still assessible with the old class name, with the code
```
bom_dlg = app.window(title_re=".*BOM.*")
bom_dlg.print_control_identifiers(depth=2)
bottom = bom_dlg[u'Afx:5DF50000:1008']
# bottom.draw_outline()
bottom.print_control_identifiers(depth=2)
```

it prints out
```
Afx:61EF0000:1008 - ''    (L726, T232, R1322, B619)
<pywinauto.controls.hwndwrapper.HwndWrapper object at 0x0497E570>
[u'', u'Afx:61EF0000:1008', u'1', u'0']
child_window(class_name="Afx:61EF0000:1008")
   | 
   | Custom Container Class - 'Custom  Container'    (L729, T240, R1316, B613)
   |  ....
```

**Comment by vasily-v-ryabov** [comment] 2016-11-18 13:46
`__getitem__` access uses "best match" algorithm which is resistant to typos and small variations. `bom_dlg[u'Afx:5DF50000:1008']` is an equivalent of `bom_dlg.child_window(best_match=u'Afx:5DF50000:1008')`. It can be matched against changed but similar class name.

Can you get the edit boxes and check boxes using `Inspect.exe`?

**Comment by hastelloy** [comment] 2016-11-18 14:06
ok, `best_match` do a great job.

> Can you get the edit boxes and check boxes using Inspect.exe?

No, can't. Maybe those are customized GUI controls and can't be recoginzed. [Here ](http://www.synactive.com/download/sap%20gui%20scripting/sap%20gui%20scripting%20api.pdf)I found an introduction on the SAP GUI.

**Comment by airelil** [comment] 2016-11-18 20:36
@hastelloy, my guess is that you don't see any child controls because they are not belongs to the main application process. Maybe you should try to look around for other processes. Such as another SAP app or a explorer.exe

**Comment by airelil** [comment] 2016-11-22 19:54
@hastelloy, any updates on it ?

**Comment by hastelloy** [comment] 2016-11-23 07:44
@airelil, I have gone through all the processes, didn't find anything.
From the [document ](http://www.synactive.com/download/sap%20gui%20scripting/sap%20gui%20scripting%20api.pdf)of SAP, the area is called as GUIUserArea, my guess is the controls is encapsuled into this control and doesn't disclosed the child control as common. So this may due to some tricks of SAP, nothing to do with pywinauto...

**Comment by vasily-v-ryabov** [comment] 2017-02-07 15:48
OK, closing this since it's out of scope for accessibility technologies.

**Closed by vasily-v-ryabov** 2017-02-07 15:48 UTC
Labels: question
