### ISSUE TITLE
Is there any way to use [xpath] string with app.window.window ?

### ISSUE THREAD

**Issue by Heidernlee** [pywinauto/pywinauto#1022] opened 2020-12-10 07:16 UTC
It's very easier to get [xpath] string by using [WinAppDriver UIRecorder] than spy++ or other Tools ,
So I decided to [Run Apps]=>[get xpath string using UIRecorder]=>[write auto-run script using pywinauto]  
but app.by_xpath() is not released yet, am I right ?

So is there any way to use [xpath] string now? like:
xpath string : "//Window[@Name=\'DF\']/MenuBar[@Name=\'Application\'][@AutomationId=\'MenuBar\']/MenuItem[@Name=\'Option\']"
pywinauto : 
app.window(name='DF').child_window(name='Application').child_window(name='Option') ?

**Comment by vasily-v-ryabov** [comment] 2020-12-23 09:03
Duplicate of #896. It's planned for next year. Also we don't plan to integrate with Microsoft's UI Recorder. We're planning to implement our own recorder (prototype is here: https://github.com/pywinauto/pywinauto/pull/701).

**Closed** 2020-12-23 09:03 UTC
Labels: duplicate

**Comment by Heidernlee** [comment] 2020-12-23 09:28
@vasily-v-ryabov 
Thanks for your response. UIRecorder is a good tool for recording XPath of Elements, 
but it cannot record Window-Handlers while Hide+Show Windows.
Hope you guys could do it better. Thanks.
