### ISSUE TITLE
Unable to check/uncheck Treeview element (uia, win64)

### ISSUE THREAD

**Issue by alexgoryachev** [pywinauto/pywinauto#397] opened 2017-08-02 01:38 UTC
I'm not able to check/uncheck Treeview elements (uia,  64 bit, py2.7).
look at the attached picture.
![tree](https://user-images.githubusercontent.com/13759203/28853807-e37e21da-76e7-11e7-9e40-ac14d91ed6a0.png)

I can get a tree element: 
element23 =  lower.child_window(title="element23", control_type="TreeItem")
and I expend it easily 
element23.expand() 

But the following commands do not work
element23.toggle() – WindowSpecification class has no 'toggle' method
element23.click() – WindowSpecification class has no 'click' method
element23.click_input() – clicks on “23” but doesn’t uncheck
element23.double_click_input()   clicks on “23” but doesn’t uncheck

**Comment by airelil** [comment] 2017-08-02 06:42
Hi @alexgoryachev, you can find a couple of examples how to work with TreeView in our unit tests. For instance, you may take a look at [test_tv_item_select](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/unittests/test_uiawrapper.py#L1370).

**Comment by vasily-v-ryabov** [comment] 2017-08-02 09:47
Hi Alex. Which patterns are available for this element in Inspect.exe? Can you screenshot all the properties in Inspect.exe for this element?

**Comment by alexgoryachev** [comment] 2017-08-02 16:52
Sure.

HelpText:	""
ExpandCollapse.ExpandCollapseState:	Collapsed (0)
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	"Expand"
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	"Element 25"
LegacyIAccessible.Role:	outline item (0x24)
LegacyIAccessible.State:	checked,collapsed,focusable,selectable (0x300410)
LegacyIAccessible.Value:	""
SelectionItem.IsSelected:	false
SelectionItem.SelectionContainer:	"" tree
Toggle.ToggleState:	On (1)
IsAnnotationPatternAvailable:	false
IsDragPatternAvailable:	false
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	false
IsExpandCollapsePatternAvailable:	true
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	true
IsScrollPatternAvailable:	false
IsSelectionItemPatternAvailable:	true
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	false
IsSpreadsheetPatternAvailable:	false
IsStylesPatternAvailable:	false
IsSynchronizedInputPatternAvailable:	false
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	false
IsTextEditPatternAvailable:	false
IsTextPatternAvailable:	false
IsTextPattern2Available:	false
IsTogglePatternAvailable:	true
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	false
IsValuePatternAvailable:	false
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
IsCustomNavigationPatternAvailable:	false
FirstChild:	[null]
LastChild:	[null]
Next:	"Element 26" tree item
Previous:	"Element 24" tree item
Other Props:	Object has no additional properties
Children:	Container has no children
Ancestors:	"Lower" tree item
	"Pair" tree item
	"E:\TD\Cases\2346901\1_1_0_2346901USTreat.adf" tree item
	"" tree
	"Scene Tree" dialog
	"" pane
	"Scene Tree" pane
	"Treat Inc. - Proprietary  Restricted" window
	"Desktop" pane
	[ No Parent ]

**Comment by airelil** [comment] 2017-08-02 17:53
Maybe you should try to adjust your click coordinates. As in the unit test mentioned above, obtain the middle point of the item's rectangle and adjust to the left until you hit the check box. Notice the usage of absolute coordinates.

**Comment by alexgoryachev** [comment] 2017-08-02 18:52
It  works, but is it the right way ?
element23.click_input()
x, y = win32api.GetCursorPos()
pywinauto.mouse.click(button='left', coords=(x - 50, y))

**Comment by airelil** [comment] 2017-08-03 01:12
Alex, I thought to go with the code from the unitest (did you look into it?) :
Get item's rectangle middle point
Adjust the left
Use item.click_input, but the adjusted coordinates marked as absolute. 

Sorry, I'm not at my PC right now. Maybe I'll come up later with a complete example

**Comment by alexgoryachev** [comment] 2017-08-03 06:06
I'll check the unitest example tomorrow  at CA time. Thank you so much.

**Comment by airelil** [comment] 2017-08-03 06:32
@alexgoryachev, I meant something like this:
```python
            itm = ctrl.get_item((0, 3, 2)) # get the item from the TreeView control

            itm.ensure_visible()
            coords = itm.rectangle().mid_point()
            coords.x -= 50
            itm.click_input(coords=coords, absolute=True)
```

Notice that we can use ```get_item``` method of TreeView wrapper and specify a path to the item as a tuple of numbers or strings
```
        * **path** a path to the item to return. This can be one of
          the following:

          * A string separated by \\ characters. The first character must
            be \\. This string is split on the \\ characters and each of
            these is used to find the specific child at each level. The
            \\ represents the root item - so you don't need to specify the
            root itself.
          * A list/tuple of strings - The first item should be the root
            element.
          * A list/tuple of integers - The first item the index which root
            to select. Indexing always starts from zero: get_item((0, 2, 3))
```

**Comment by vasily-v-ryabov** [comment] 2018-01-25 17:44
Hi @alexgoryachev did you resolve this issue finally?

**Comment by alexgoryachev** [comment] 2018-01-26 07:04
solved

**Closed** 2018-01-26 07:04 UTC
Labels: question

**Comment by madhavankumar** [comment] 2018-07-13 06:04
I have a Treeview view but when I get the element and try to get the coordinates from the rectangle(), I get an error - 

AttributeError: '_treeview_element' object has no attribute 'rectangle'

From Swapy, I do see the Rectangle property

![image](https://user-images.githubusercontent.com/5941859/42675146-c46557e6-8640-11e8-90a4-696851cf252c.png)
In Inspect,
![image](https://user-images.githubusercontent.com/5941859/42675193-f6c61202-8640-11e8-8eed-34bd9341ae2b.png)

How Do I check/uncheck the checkbox in a Treeview?

**Comment by vasily-v-ryabov** [comment] 2018-07-13 07:12
Hi @madhavankumar this is a mismatch between Inspect,exe and "win32" backend you use. You have 2 choices:

 1. Continue using "win32" backend and call `.click(where="check")` along with `.is_cheched()` for `_treeview_element` object. `click` can be replaced by `click_input` if you want real mouse cursor manipulation.

 2. Switch to `Application(backend="uia")` and re-write the whole script (because the hierarchy is usually different for these 2 backends).

P.S. Please open new issue next time if the old issue was closed. The problem may look similar, but the root cause is not.

**Comment by madhavankumar** [comment] 2018-07-17 03:18
@vasily-v-ryabov - I will open a new issue next time. Apologies for that. I wanted to avoid duplication. I use win32 backend. I used `.click_input(where="check")` worked like a charm. Thank you very much!
