### ISSUE TITLE
Able to get the button text but not able to click

### ISSUE THREAD

**Issue by gowtham7774** [pywinauto/pywinauto#1252] opened 2022-11-03 14:49 UTC
## Expected Behavior
should be able to click with pywinauto click() option

## Actual Behavior
Not able to click

## Short Example of Code to Demonstrate the Problem

code snippet:

confirmWin = self.win.connect(title_re="Import Autosaved .*", visible_only=True)
confirmWin.top_window().set_focus()
confirmWin.ImportAutosavedExportDialog[u'&YesButton'].click()

print(confirmWin.ImportAutosavedExport.print_control_identifiers())
********************************************************************************
Control Identifiers: 

Dialog - 'Import Autosaved Export'    (L507, T317, R866, B473)
['Import Autosaved ExportDialog', 'Import Autosaved Export', 'Dialog']
child_window(title="Import Autosaved Export", class_name="#32770")
   |
   | Button - '&Yes'    (L689, T437, R764, B460)
   | ['Button', '&YesButton', '&Yes', 'Button0', 'Button1']
   | child_window(title="&Yes", class_name="Button")
   |
   | Button - '&No'    (L773, T437, R848, B460)
   | ['Button2', '&NoButton', '&No']
   | child_window(title="&No", class_name="Button")
   |
   | Static - 'During a Remove on 11/03/2022 02:26:19, JIMS exported the configuration for version 1.41.\nDo you want to import it now?'    (L521, T366, R833, B407
)

## Specifications

  - Pywinauto version: 0.6.8 
  - Python version and bitness: python 3.9
  - Platform and OS: windows

**Comment by Wolverine1122** [comment] 2022-11-24 07:14
I can't reproduce your issue as I don't know the program nor see a screenshot of layout.

But for some buttons, `click` doesn't work. Try `click_input`

**Comment by vasily-v-ryabov** [comment] 2023-01-03 15:57
Yes, `click()` is an alias for `invoke()` for `backend="uia"`.
For "win32" backend it's also not a natural click. But sometimes a pause helps because of lazy initialization of a dialog.

Use `click_input()` for real mouse click. In the future please provide backend name used for `Application` object creation and the full traceback of the error.

I'm going to close this issue as not a bug (the app side issue). If you still think it's an issue in pywinauto, please re-open.

**Closed by vasily-v-ryabov** 2023-01-03 15:57 UTC
Labels: question
