### ISSUE TITLE
Multiple same client will be failure

### ISSUE THREAD

**Issue by gucasbrg** [pywinauto/pywinauto#214] opened 2016-07-26 03:31 UTC
hi,
 I use pywinauto in order to control multiple same client ,but top_window_() can't get correct client,
Seemed to be someone in them

**Comment by vasily-v-ryabov** [comment] 2016-07-26 20:00
`top_window_()` is not recommended way to access dialogs because it returns window specification for the active dialog at the moment one called this method. It's OK for debugging when you have static picture (and probably one top-level window for the app), but for production it's better to use dialog name to create correct WindowSpecification object.

```python
app.MainWindow.MenuSelect('File->Open')
app.top_window_().Edit.SetText('file.txt') # may fail because it still matches MainWindow
```
Instead:
```python
app.MainWindow.MenuSelect('File->Open')
app.Open.Edit.SetText('file.txt') # would work because it implicitly waits while "Open" dialog exists

app.Open.Wait('ready') # explicit wait that returns DialogWrapper object
```

**Comment by gucasbrg** [comment] 2016-08-07 22:23
Doesn't seem to work very well for multiple clients.
ex,have two notepad(A,B),want to open dialog for A,maybe mistake for opening B,
even use Open

**Comment by airelil** [comment] 2016-08-08 00:42
@gucasbrg, I you could provide us a small script that reproduces your problem it would be much better than just trying to make guesses.

**Comment by vasily-v-ryabov** [comment] 2016-08-23 08:12
Closing since no reaction during a month. @gucasbrg, if it's still important for you, please re-open the issue with more detailed steps to reproduce.

**Closed by vasily-v-ryabov** 2016-08-23 08:12 UTC
Labels: invalid, question
