### ISSUE TITLE
Is there a function to force Pywinauto to empty its caches to update wrapper.rectangle() ?

### ISSUE THREAD

**Issue by beuaaa** [pywinauto/pywinauto#1025] opened 2020-12-21 16:21 UTC
## Expected Behavior
When Excel detects that a file was incorrectly closed during the last run, a 'Document recovery' panel appears. When this panel is closed, the tabs are shifted. But Pywinauto does not update the new positions. A call of wrapper_of_tab.rectangle() gives the position of the tab before the panel is closed.

Is there a function to force Pywinauto to empty its caches to update the positions?

## Actual Behavior
In the screenshot below, the left-most green rectangle corresponds to the current behaviour while the correct position is given by the other green rectangle.
[Screen capture](https://i.ibb.co/ctbJCXN/Pywinauto.png)

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: 3.8.3 64bit
  - Platform and OS: Windows 10

**Comment by TesterNick** [comment] 2021-10-01 13:57
The problem is bigger. Elements are not found on dynamic apps. Pywinauto does not refresh cache when window is changed. One of the features in the app I'm testing is searching on database. It shows best results and a button for all results which appears when the search is completed. if the base is small (<20 GB) the button is shown in a moment and can be found. But if the base is quite large (>200 GB), the search can takes several seconds, and the button is never found, though it is visible on the screen and in inspect.exe

**Comment by vasily-v-ryabov** [comment] 2021-12-13 15:52
Hi @TesterNick sorry for long waiting. Please try again. `import pywinauto` works for me after one more fix.

**Comment by dmwyatt** [comment] 2021-12-31 21:05
I came across this issue when searching the issues for `ModuleNotFoundError: No module named 'pywinauto.windows'`.

I just installed the `atspi` branch in an attempt to get the fixes from #922, but it doesn't work because of that error.

**Comment by vasily-v-ryabov** [comment] 2022-01-01 11:58
Hi @dmwyatt the fix is not merged to `atspi` branch yet. Please try this branch:
```
pip uninstall -y pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/refs/heads/cache_disable_global.zip
```

**Comment by vasily-v-ryabov** [comment] 2022-02-20 12:11
@TesterNick @dmwyatt can someone confirm the fix in my branch is working?

**Comment by dmwyatt** [comment] 2022-02-20 18:43
I can't remember where I was originally having this problem, but I can confirm that installing `cache_disable_global.zip` and then importing pywinauto works fine.

**Closed** 2022-02-27 12:17 UTC
Labels: bug, Priority-Critical, refactoring_critical

**Comment by vasily-v-ryabov** [comment] 2022-02-27 17:44
The fix is merged (closed automatically). Hope we will be able to make a big release before June.
